### ISSUE TITLE
Better handle macro serialization errors and bad state in general

### ISSUE THREAD

**Issue by z3z1ma** [TobikoData/sqlmesh#1063]
Traceback from invalid, irreconcilable state due to faulty serialized macro. Macro was actually valid/working for many weeks. But at some point became invalid. Likely due to change in sqlglot. 

```
...more snapshots
2023-06-29 09:32:46,854 - sqlmesh.core.state_sync.engine_adapter - DEBUG - name='analytics_staging.stg_salesforce__users' identifier='4002002596' mapped to name='analytics_staging.stg_salesforce__users' identifier='96923916'. (engine_adapter.py:736)
Traceback (most recent call last):

  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/macros.py", line 122, in send
    return func(self, *args)

  File 'macros/macros.py' (or imported file), line 5, in dlt_dedupe
    def dlt_dedupe(evaluator, table_, primary_keys):
        source_table = exp.Table(this=table_.name, catalog=table_.table)
        load_table = exp.Table(this='_dlt_loads', catalog=source_table.catalog)
        for key in primary_keys.expressions:
            key.set('table', source_table.alias_or_name)


  File "/.../.../.venv/lib/python3.10/site-packages/sqlglot/expressions.py", line 202, in alias_or_name
    return self.alias or self.name

  File "/.../.../.venv/lib/python3.10/site-packages/sqlglot/expressions.py", line 2289, in name
    return self.this.name

AttributeError: 'str' object has no attribute 'name'
Traceback (most recent call last):
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/macros.py", line 122, in send
    return func(self, *args)
  File "<string>", line 5, in dlt_dedupe
  File "/.../.../.venv/lib/python3.10/site-packages/sqlglot/expressions.py", line 202, in alias_or_name
    return self.alias or self.name
  File "/.../.../.venv/lib/python3.10/site-packages/sqlglot/expressions.py", line 2289, in name
    return self.this.name
AttributeError: 'str' object has no attribute 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/renderer.py", line 147, in render
    expression = macro_evaluator.transform(expression)  # type: ignore
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/macros.py", line 159, in transform
    transformed = evaluate_macros(query)
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/macros.py", line 151, in evaluate_macros
    exp.replace_children(
  File "/.../.../.venv/lib/python3.10/site-packages/sqlglot/expressions.py", line 5691, in replace_children
    for child_node in ensure_collection(fun(cn, *args, **kwargs)):
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/macros.py", line 152, in <lambda>
    node, lambda n: n if isinstance(n, exp.Lambda) else evaluate_macros(n)
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/macros.py", line 151, in evaluate_macros
    exp.replace_children(
  File "/.../.../.venv/lib/python3.10/site-packages/sqlglot/expressions.py", line 5691, in replace_children
    for child_node in ensure_collection(fun(cn, *args, **kwargs)):
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/macros.py", line 152, in <lambda>
    node, lambda n: n if isinstance(n, exp.Lambda) else evaluate_macros(n)
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/macros.py", line 151, in evaluate_macros
    exp.replace_children(
  File "/.../.../.venv/lib/python3.10/site-packages/sqlglot/expressions.py", line 5691, in replace_children
    for child_node in ensure_collection(fun(cn, *args, **kwargs)):
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/macros.py", line 152, in <lambda>
    node, lambda n: n if isinstance(n, exp.Lambda) else evaluate_macros(n)
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/macros.py", line 156, in evaluate_macros
    return self.evaluate(node)
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/macros.py", line 194, in evaluate
    result = self.send(func.name, *func.expressions)
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/macros.py", line 125, in send
    raise MacroEvalError(f"Error trying to eval macro.") from e
sqlmesh.utils.errors.MacroEvalError: Error trying to eval macro.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../.../.venv/bin/cdf", line 8, in <module>
    sys.exit(app())
  File "/.../.../.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/.../.../.venv/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/.../.../.venv/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/.../.../.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/.../.../.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/.../.../.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/.../.../.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/.../.../.venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/cli/main.py", line 413, in migrate
    ctx.obj.migrate()
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/context.py", line 989, in migrate
    self._new_state_sync().migrate()
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/state_sync/common.py", line 36, in wrapper
    return func(self, *args, **kwargs)
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/state_sync/engine_adapter.py", line 623, in migrate
    self._migrate_rows()
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/state_sync/engine_adapter.py", line 698, in _migrate_rows
    new_snapshot.fingerprint = fingerprint_from_model(
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/snapshot/definition.py", line 890, in fingerprint_from_model
    for table in model.depends_on
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/model/definition.py", line 770, in depends_on
    query = self.render_query(optimize=False)
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/model/definition.py", line 738, in render_query
    query = self._query_renderer.render(
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/renderer.py", line 283, in render
    super().render(
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/core/renderer.py", line 149, in render
    raise_config_error(f"Failed to resolve macro for expression. {ex}", self._path)
  File "/.../.../.venv/lib/python3.10/site-packages/sqlmesh/utils/errors.py", line 90, in raise_config_error
    raise error_type(f"{msg} at '{location}'")
sqlmesh.utils.errors.ConfigError: Failed to resolve macro for expression. Error trying to eval macro. at '.'
```

Recommendation for UX:

This encapsulates both the macro serialization failure  and invalid state since they are closely related 

I can see a combination of exception catching and user prompting being appropriate with various reconciliation strategies and a "best path" approach based on the exceptions that is improved over time (this shouldnt be common anyway)

Think of a 1,2,3 where the 1 is recommended (IE clear snapshot X), 2 or 3 would be (clear environment), etc. and user can choose not to reconcile and simply fail out if they want to handle themselves or look elsewhere.

**Comment by GeorgeSittas** [comment]
Commenting on the issue at hand:

> Macro was actually valid/working for many weeks.

There's an error in how the `Table` expression is constructed here (based on the stack trace):

```python
load_table = exp.Table(this='_dlt_loads', catalog=source_table.catalog)
```

If you choose to manually construct the SQLGlot expression, then you need to make sure the relevant AST contracts are satisfied. In particular, the `Table` arguments should be references to `Identifier` expressions, so that e.g. `table.name` can safely delegate to `Identifier.name`. Alternatively, you can use the `exp.to_table` helper to construct the expression.

**Comment by GeorgeSittas** [comment]
Btw I plan to take a look at this soon, your UX suggestion seems legit @z3z1ma.
