### ISSUE TITLE
connection guide

### ISSUE THREAD

**Issue by samukweku** [TobikoData/sqlmesh#1192]
- is there a guide/tutorial that walks you through connecting to cloud databases (bigquery, databricks, ...). I tried connecting to bigquery, and it just felt like i was guessing a lot of things, based on the error messages it gives :
```
Location single-region does not support this operation.

ProjectId and DatasetId must be non-empty
```

i probably am missing something obvious, but the guide in the connections page doesn't really help.

open to suggestions on how to go about this. In addition, is there any guide for connecting via the python interface? currently trying the cli route.

```gateways:
    bigquery:
        connection:
            type: bigquery
            method: service-account
            project: s*****
            location: single-region
            keyfile: service_account.json
```

**Comment by eakmanrq** [comment]
The best of what we have today is in the docs. Definitely want to improve it over time as we better understand different patterns people have for setting up their connections.

In terms of the location issue, I think the problem is that it needs to be a region or multi-region. I don't think `single-region` is a valid value. If you leave this undefined then it will use the default region defined by your client. If you know all of your datasets are in a specific region (like `us-west1`) then you can pass that in.

Do you have the stack trace that produced `ProjectId and DatasetId must be non-empty`? This is a bit surprising. When you define your models, are you included a dataset name? So `db.table` would have a dataset of `db`?

**Comment by samukweku** [comment]
I want to get a hang of it, so I can better explain its benefits to clients. I currently use dbt as a data engineer in a fintech; i do feel sqlmesh can make thing simpler. 

back to my issue, i removed the location entry in yaml, enabled billing in gcp, and got this error: 

```
(sqlmesh) sam@pop-os:~/jaffle_shop$ sqlmesh --gateway bigquery plan
======================================================================
Successfully Ran 1 tests against duckdb
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sam/miniforge3/envs/sqlmesh/bin/sqlmesh", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/cli/__init__.py", line 20, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/cli/main.py", line 236, in plan
    context.plan(environment, restate_models=restate_models, **kwargs)
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/core/context.py", line 629, in plan
    context_diff=self._context_diff(environment or c.PROD, create_from=create_from),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/core/context.py", line 922, in _context_diff
    snapshots=snapshots or self.snapshots,
                           ^^^^^^^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/core/context.py", line 408, in snapshots
    prod = self.state_reader.get_environment(c.PROD)
           ^^^^^^^^^^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/core/context.py", line 328, in state_reader
    self._state_reader = self.state_sync
                         ^^^^^^^^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/core/context.py", line 320, in state_sync
    self._state_sync.migrate()
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/core/state_sync/common.py", line 36, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/core/state_sync/engine_adapter.py", line 418, in migrate
    super().migrate(skip_backup)
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/core/state_sync/base.py", line 388, in migrate
    migration.migrate(self)
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/migrations/v0004_environmnent_add_finalized_at.py", line 19, in migrate
    engine_adapter.execute(alter_table_exp)
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/bigquery.py", line 403, in execute
    retry.retry_target(
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
           ^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/bigquery.py", line 381, in _retryable_execute
    results = self.cursor._query_job.result(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py", line 1520, in result
    do_get_result()
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
           ^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py", line 1510, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/miniforge3/envs/sqlmesh/lib/python3.11/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Column already exists: finalized_ts at [1:46]

Location: US
Job ID: e512f57b-0772-495d-97e8-771f0dd50358
```

this is the yaml I used: 

```py
gateways:
    bigquery:
        connection:
            type: bigquery
            method: service-account
            project: sammywemmy-393111
            keyfile: service_account.json
```

**Comment by samukweku** [comment]
thanks for the quick response @eakmanrq

**Comment by samukweku** [comment]
it does show sqlmesh setting up in bigquery: 

![image](https://github.com/TobikoData/sqlmesh/assets/25709809/9820fd11-0a6c-4d74-aa66-414125871db2)


however when i run `sqlmesh plan dev` it does not build a dev environment, and still outputs the error message: 

```
google.api_core.exceptions.BadRequest: 400 Column already exists: finalized_ts at [1:46]
```

**Comment by eakmanrq** [comment]
@samukweku I think you hit an error while you were doing the upgrade which got you in a weird state. Can you try deleting the `sqlmesh` dataset and then running your command again? That will give you a fresh start.

**Comment by samukweku** [comment]
awesome @eakmanrq, works fine. got a better handle of how things work ( i think). 

```
# config.yaml 
gateways:
    bigquery:
        connection:
            type: bigquery
            method: service-account
            project: sammywemmy-393111
            keyfile: service_account.json
            location: 'australia-southeast1'


model_defaults:
    dialect: bigquery
```

```
# output 
New environment `prod` will be created from `prod`
Summary of differences against `prod`:
└── Added Models:
    ├── jaffleshop.stg_customers
    └── jaffleshop.raw_customers
Models needing backfill (missing dates):
└── jaffleshop.stg_customers: 2023-07-23 - 2023-07-23
Apply - Backfill Tables [y/n]: y
jaffleshop.stg_customers ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0% • 1/1 • 0:00:05

All model batches have been executed successfully

Virtually Updating 'prod' ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0% • 0:00:06

The target environment has been updated successfully
```

I noticed that when running `create_external_models`, it picks the last written file and overwrites the schema.yaml content. If i have just one model, it is fine, multiple models and it just writes the schema for only one.

```
#stg_customers.sql file
MODEL (
  name jaffleshop.stg_customers,
  kind FULL,
  cron '@daily',
);

SELECT
  id as customer_id,
  first_name,
  last_name
FROM
    jaffleshop.raw_customers


# stg_orders.sql file
MODEL (
  name jaffleshop.stg_orders,
  kind FULL,
  cron '@daily',
);

SELECT
  id as order_id,
  user_id as customer_id,
  order_date,
  status
FROM
    jaffleshop.raw_orders
```

Only one schema is created:

```
- name: jaffleshop.raw_orders
  columns:
    id: INT
    user_id: INT
    order_date: DATE
    status: TEXT
```

If i manually copy the schema, and rerun `create_external_models`, an empty list is dumped into the schema.yaml, overwriting the existing entries

**Comment by eakmanrq** [comment]
Hmm. We recently had a fix go in that sounds related to this: https://github.com/TobikoData/sqlmesh/issues/1132

Can you make sure you are using `0.22.0` or greater and see if there is still an issue?

**Comment by samukweku** [comment]
thanks @eakmanrq , upgraded to version 22 and all works fine. need to get my head around the backfill concept. thanks again. will contribute to the repo as i understand things better.

**Comment by samukweku** [comment]
Another snag @eakmanrq how do I reset everything, so that sqlmesh does not keep a history of changes? Start afresh completely, like a full reset?

**Comment by eakmanrq** [comment]
What you can do is drop all schemas that exist with `sqlmesh` in the name. If you do that then you just have views left for your different environments. So for example if you were running the sushi example then you would have a `raw` and `sushi` schema left. Those can be dropped too as long as you don't have other tables in there that you don't want to drop. When you run SQLMesh again it run like it is starting for the first time.

**Comment by eakmanrq** [comment]
@samukweku If you have more question feel free to ask in our [Slack](https://tobikodata.com/slack). We are going to close this since the original question has been answered.

**Comment by ImranZulkiflee** [comment]
![Error1](https://github.com/TobikoData/sqlmesh/assets/92116955/864dc680-d478-4b4e-9446-52fb2c831635)
i probably am missing something obvious, but the guide in the connections page doesn't really help.

open to suggestions on how to go about this. In addition, is there any guide for connecting via the python interface? currently trying the cli route.

**Comment by ImranZulkiflee** [comment]
![Error1](https://github.com/TobikoData/sqlmesh/assets/92116955/e9162ae0-720f-41db-86d2-24ed4e150686)
I currently faced an error regarding the location of big query where mine is asia-southeast1                         
![Error2](https://github.com/TobikoData/sqlmesh/assets/92116955/2911c9ec-dbfd-448d-8191-f58bdfe27e96)

open to suggestions on how to go about this. In addition, is there any guide for connecting via the python interface? currently trying the cli route.

**Comment by samukweku** [comment]
It says that it does not exist in that location. Maybe just check that. It is possible that you would get a better response if you opened a new issue since this is closed. You can always reference this in the new issue @ImranZulkiflee
