### ISSUE TITLE
error parsing array type

### ISSUE THREAD

**Issue by cmvarmour** [TobikoData/sqlmesh#1457]
Hey guys, I found some failing DDL which is valid in postgres

Model definition:
```
MODEL (
  name example.test,
  kind FULL
);

SELECT ARRAY[]::INTEGER[] AS foo
;
```

Debug error output:
```
Creating new model versions ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0% • pending • 0:00:002023-09-21 22:49:45,115 - sqlmesh.core.snapshot.evaluator - INFO - Creating schema 'sqlmesh__example' (evaluator.py:586)
2023-09-21 22:49:45,116 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
CREATE SCHEMA IF NOT EXISTS "sqlmesh__example" (base.py:1237)
2023-09-21 22:49:45,154 - sqlmesh.core.model.definition - DEBUG - Rendered query for 'example.test':
  SELECT
    CAST([][] AS INT[]) AS "foo" (definition.py:944)
2023-09-21 22:49:45,154 - sqlmesh.core.snapshot.evaluator - INFO - Creating table 'sqlmesh__example.example__test__3431843819' (evaluator.py:848)
2023-09-21 22:49:45,154 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
CREATE TABLE IF NOT EXISTS "sqlmesh__example"."example__test__3431843819" ("foo" INT[]) (base.py:1237)
2023-09-21 22:49:45,185 - sqlmesh.core.snapshot.evaluator - INFO - Dry running model 'example.test' (evaluator.py:860)
2023-09-21 22:49:45,186 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
SELECT CAST([][] AS INT[]) AS "foo" (base.py:1237)
Creating new model versions ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0% • pending • 0:00:00
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 67, in _process_node
    self.fn(node)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 163, in <lambda>
    lambda s_id: fn(snapshots_by_id[s_id]),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 283, in <lambda>
    lambda s: self._create_snapshot(s, snapshots, on_complete),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 445, in _create_snapshot
    evaluation_strategy.create(snapshot, target_table_name, **render_kwargs)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 861, in create
    self.adapter.fetchall(ctas_query)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 1138, in fetchall
    self.execute(
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/mixins.py", line 146, in execute
    super().execute(
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 1238, in execute
    self.cursor.execute(sql, **kwargs)
psycopg2.errors.SyntaxError: syntax error at or near "["
LINE 1: SELECT CAST([][] AS INT[]) AS "foo"
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/sqlmesh", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/cli/main.py", line 291, in plan
    context.plan(environment, restate_models=restate_models, select_models=select_models, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/context.py", line 793, in plan
    self.console.plan(plan, auto_apply)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/console.py", line 450, in plan
    self._show_options_after_categorization(plan, auto_apply)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/console.py", line 542, in _show_options_after_categorization
    self._prompt_backfill(plan, auto_apply)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/console.py", line 653, in _prompt_backfill
    plan.apply()
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/plan/definition.py", line 320, in apply
    self._apply(self)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/context.py", line 825, in apply
    raise e
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/context.py", line 820, in apply
    self._scheduler.create_plan_evaluator(self).evaluate(plan)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/plan/evaluator.py", line 83, in evaluate
    self._push(plan)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/plan/evaluator.py", line 140, in _push
    self.snapshot_evaluator.create(
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 281, in create
    concurrent_apply_to_snapshots(
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 161, in concurrent_apply_to_snapshots
    return concurrent_apply_to_dag(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 203, in concurrent_apply_to_dag
    ).run()
      ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 62, in run
    self._finished_future.result()
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
sqlmesh.utils.concurrency.NodeExecutionFailedError: Execution failed for node name='example.test' identifier='4105862179'
```

**Comment by GeorgeSittas** [comment]
Thanks for the report @cmvarmour!

**Comment by cmvarmour** [comment]
np 🙏 

thank you george
