### ISSUE TITLE
error parsing model DDL

### ISSUE THREAD

**Issue by cmvarmour** [TobikoData/sqlmesh#1458]
Hey guys, I've found some DDL which is valid in postgres but failing in sqlmesh

# Model definition
```
MODEL (
  name demo.fail,
  kind FULL
);

SELECT count(DISTINCT item_id) FILTER (WHERE num_orders > 0) AS fail_count
FROM sqlmesh_example.full_model
;
```

# debug error output
```
2023-09-21 23:20:39,559 - tzlocal - DEBUG - /etc/timezone found, contents:
 Etc/UTC
 (unix.py:63)
2023-09-21 23:20:39,559 - tzlocal - DEBUG - /etc/localtime found (unix.py:122)
2023-09-21 23:20:39,560 - tzlocal - DEBUG - 2 found:
 {'/etc/timezone': 'Etc/UTC', '/etc/localtime is a symlink to': 'Etc/UTC'} (unix.py:138)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/loader.py", line 264, in _load
    expressions = parse(
                  ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/dialect.py", line 590, in parse
    for expression in parser.parse(chunk, sql):
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 943, in parse
    return self._parse(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 1009, in _parse
    expressions.append(parse_method(self))
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/dialect.py", line 134, in _parse_statement
    return self.__parse_statement()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 1199, in _parse_statement
    expression = self._parse_set_operations(expression) if expression else self._parse_select()
                                                                           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 2066, in _parse_select
    projections = self._parse_projections()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 2018, in _parse_projections
    return self._parse_expressions()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 4669, in _parse_expressions
    return self._parse_csv(self._parse_expression)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 4623, in _parse_csv
    parse_result = parse_method()
                   ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3076, in _parse_expression
    return self._parse_alias(self._parse_conjunction())
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3079, in _parse_conjunction
    return self._parse_tokens(self._parse_equality, self.CONJUNCTION)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 4637, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3082, in _parse_equality
    return self._parse_tokens(self._parse_comparison, self.EQUALITY)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 4637, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3085, in _parse_comparison
    return self._parse_tokens(self._parse_range, self.COMPARISON)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 4637, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3088, in _parse_range
    this = self._parse_bitwise()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3195, in _parse_bitwise
    this = self._parse_term()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3220, in _parse_term
    return self._parse_tokens(self._parse_factor, self.TERM)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 4637, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/dialects/postgres.py", line 346, in _parse_factor
    return self._parse_tokens(self._parse_exponent, self.FACTOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 4637, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/dialects/postgres.py", line 349, in _parse_exponent
    return self._parse_tokens(self._parse_unary, self.EXPONENT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 4637, in _parse_tokens
    this = parse_method()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3228, in _parse_unary
    return self._parse_at_time_zone(self._parse_type())
                                    ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3237, in _parse_type
    this = self._parse_column()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3417, in _parse_column
    this = self._parse_field()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3521, in _parse_field
    or self._parse_function(anonymous=anonymous_func)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 3583, in _parse_function
    return self._parse_window(this)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 4394, in _parse_window
    this = self.expression(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 1073, in expression
    return self.validate_expression(instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 1093, in validate_expression
    self.raise_error(error_message)
  File "/usr/local/lib/python3.11/site-packages/sqlglot/parser.py", line 1053, in raise_error
    raise error
sqlglot.errors.ParseError: Required keyword: 'expression' missing for <class 'sqlglot.expressions.Filter'>. Line 6, Col: 55.
  MODEL (
  name demo.fail,
  kind FULL
);

SELECT count(DISTINCT item_id) FILTER (WHERE num_orders > 0) AS fail_count
FROM sqlmesh_example.full_model
;


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sqlmesh", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/cli/main.py", line 83, in cli
    context = Context(
              ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/context.py", line 288, in __init__
    self.load()
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/context.py", line 383, in load
    project = self._loader.load(self, update_schemas)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/loader.py", line 110, in load
    models = self._load_models(macros, jinja_macros)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/loader.py", line 241, in _load_models
    models = self._load_sql_models(macros, jinja_macros)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/loader.py", line 284, in _load_sql_models
    model = cache.get_or_load_model(path, _load)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/loader.py", line 405, in get_or_load_model
    model = self._model_cache.get_or_load(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/model/cache.py", line 52, in get_or_load
    loaded_model = loader()
                   ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/loader.py", line 268, in _load
    raise ConfigError(
sqlmesh.utils.errors.ConfigError: Failed to parse a model definition at '/sqlmesh/test/models/demo.sql': Required keyword: 'expression' missing for <class 'sqlglot.expressions.Filter'>. Line 6, Col: 55.
  MODEL (
  name demo.fail,
  kind FULL
);

SELECT count(DISTINCT item_id) FILTER (WHERE num_orders > 0) AS fail_count
FROM sqlmesh_example.full_model
;
.
```

**Comment by cmvarmour** [comment]
Thanks George, is there a new build I can try?

**Comment by GeorgeSittas** [comment]
I think we can release a new patch after #1462 is merged, cc @izeigerman.

**Comment by GeorgeSittas** [comment]
Released with https://github.com/TobikoData/sqlmesh/releases/tag/v0.32.4

**Comment by cmvarmour** [comment]
🙏
