### ISSUE TITLE
case 

### ISSUE THREAD

**Issue by cmvarmour** [TobikoData/sqlmesh#1467]
hey guys, i found some valid DDL which doesn't compile

using postgres dialect

# Model DDL
```
MODEL (
  name sqlmesh_example.full_model,
  kind FULL,
  cron '@daily',
  grain item_id,
  audits [assert_positive_order_ids],
);

SELECT
  item_id,
  count(distinct id) AS num_orders,
  CASE WHEN 'maybe' = 'maybe' THEN 'did_it ' || item_id || 'something else' ELSE item_id || 'a third thing' END foo
FROM
    sqlmesh_example.incremental_model
GROUP BY item_id
```

# Debug Error Output
```
FAILED processing snapshot name='sqlmesh_example.full_model' fingerprint=SnapshotFingerprint(data_hash='3850057067', metadata_hash='3413870290', parent_data_hash='2011181042', 
parent_metadata_hash='3649258194') physical_schema_=None node=Model<name: sqlmesh_example.full_model, query: SELECT item_id, COUNT(DISTINCT> 
parents=(SnapshotId(name='sqlmesh_example.incremental_model', identifier='201209289'),) audits=(ModelAudit(name='assert_positive_order_ids', dialect='postgres', skip=False, 
blocking=True, standalone=False, query=(SELECT expressions: 
  (STAR ), from: 
  (FROM this: 
    (TABLE this: 
      (MACROVAR this: this_model))), where: 
  (WHERE this: 
    (LT this: 
      (COLUMN this: 
        (IDENTIFIER this: item_id, quoted: False)), expression: 
      (LITERAL this: 0, is_string: False)))), defaults={}, expressions_=[], jinja_macros=JinjaMacroRegistry(packages={}, root_macros={}, global_objs={}, create_builtins_module=None, 
root_package_name=None, top_level_packages=[])),) intervals=[] dev_intervals=[] created_ts=1695420834554 updated_ts=1695420834554 ttl='in 1 week' 
previous_versions=(SnapshotDataVersion(fingerprint=SnapshotFingerprint(data_hash='2289469683', metadata_hash='3413870290', parent_data_hash='2011181042', 
parent_metadata_hash='3649258194'), version='2392804765', temp_version=None, change_category=<SnapshotChangeCategory.BREAKING: 1>, physical_schema_='sqlmesh__sqlmesh_example'),) 
indirect_versions={} version='1072239070' temp_version=None change_category=<SnapshotChangeCategory.NON_BREAKING: 2> unpaused_ts=None effective_from=None migrated=False
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 67, in _process_node
    self.fn(node)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/scheduler.py", line 251, in evaluate_node
    self.evaluate(snapshot, start, end, execution_time, is_dev=is_dev)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/scheduler.py", line 152, in evaluate
    self.snapshot_evaluator.evaluate(
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 206, in evaluate
    apply(query_or_df, index)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 135, in apply
    evaluation_strategy.insert(
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 977, in insert
    self.adapter.replace_query(
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/mixins.py", line 109, in replace_query
    return self._insert_append_query(table_name, query, columns_to_types)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 766, in _insert_append_query
    self.execute(exp.insert(query, table_name, columns=list(columns_to_types)))
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/mixins.py", line 142, in execute
    super().execute(
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 1273, in execute
    self.cursor.execute(sql, **kwargs)
psycopg2.errors.DatatypeMismatch: column "foo" is of type integer but expression is of type text
LINE 1: ...STINCT "incremental_model"."id") AS "num_orders", CASE WHEN ...
                                                             ^
HINT:  You will need to rewrite or cast the expression.


Traceback (most recent call last):
  File "/usr/local/bin/sqlmesh", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/cli/main.py", line 291, in plan
    context.plan(environment, restate_models=restate_models, select_models=select_models, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/context.py", line 793, in plan
    self.console.plan(plan, auto_apply)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/console.py", line 450, in plan
    self._show_options_after_categorization(plan, auto_apply)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/console.py", line 542, in _show_options_after_categorization
    self._prompt_backfill(plan, auto_apply)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/console.py", line 653, in _prompt_backfill
    plan.apply()
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/plan/definition.py", line 320, in apply
    self._apply(self)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/context.py", line 825, in apply
    raise e
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/context.py", line 820, in apply
    self._scheduler.create_plan_evaluator(self).evaluate(plan)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/plan/evaluator.py", line 85, in evaluate
    self._backfill(plan, before_promote_snapshots)
  File "/usr/local/lib/python3.11/site-packages/sqlmesh/core/plan/evaluator.py", line 120, in _backfill
    raise SQLMeshError("Plan application failed.")
sqlmesh.utils.errors.SQLMeshError: Plan application failed.
```

**Comment by tobymao** [comment]
This seems to be a query error,

```psycopg2.errors.DatatypeMismatch: column "foo" is of type integer but expression is of type text```

seems like you need to cast foo to a text type, why do you say it's a sqlmesh error?

**Comment by tobymao** [comment]
i'll close this for now but happy to help you debug or fix anything.

**Comment by cmvarmour** [comment]
you're right, item_id has a different type than my actual use case, and my problem in this report is the numeric type of item_id, if i cast as text that fixes this report, but not my actual problem

here's an updated failing DDL:

```
MODEL (
  name sqlmesh_example.full_model,
  kind FULL,
  cron '@daily',
  grain item_id,
  audits [assert_positive_order_ids],
);

SELECT
  item_id,
  count(distinct id) AS num_orders,
  CASE WHEN 'maybe' = 'maybe' THEN 'did_it ' || item_id::text || 'something else' ELSE item_id::text || 'a third thing' END || CASE WHEN item_id > 0 THEN 'fourth thing' ELSE '' END foo
FROM
    sqlmesh_example.incremental_model
GROUP BY item_id
```

**Comment by tobymao** [comment]
fixed here https://github.com/tobymao/sqlglot/commit/29550c131ce2d0209a11cd045a23683b6218c40f
