### ISSUE TITLE
postgres engine/dialect does not support 'json_array_elements... WITH ORDINALITY'

### ISSUE THREAD

**Issue by deschman** [TobikoData/sqlmesh#1619]
I have a source table loaded like this:
```
DROP TABLE IF EXISTS bronze.land_json;

CREATE TABLE bronze.land_json(
    response json NOT NULL
);

INSERT INTO bronze.land_json
VALUES ('[{"details": []}]')
;
```

This model fails:
```
MODEL (
  name sqlmesh_example.test_with_ordinality,
  kind FULL,
  cron '@daily',
  grain item_id,
  audits [assert_positive_order_ids],
);

SELECT *
FROM bronze.land_json AS lj
CROSS JOIN json_array_elements(lj.response) WITH ORDINALITY AS kv_json
;
```

With this traceback:
```
2023-10-26 08:38:27,042 - tzlocal - DEBUG - Looking up time zone info from registry (win32.py:58)
2023-10-26 08:38:27,053 - sqlmesh.cli.main - ERROR - Failed to initialize SQLMesh context (main.py:103)
Traceback (most recent call last):
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 297, in _load
    expressions = parse(
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\dialect.py", line 650, in parse
    for expression in parser.parse(chunk, sql):
  File "C:\Git\transformer\.venv\lib\site-packages\sqlglot\parser.py", line 985, in parse
    return self._parse(
  File "C:\Git\transformer\.venv\lib\site-packages\sqlglot\parser.py", line 1054, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "C:\Git\transformer\.venv\lib\site-packages\sqlglot\parser.py", line 1095, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 11, Col: 48.
  ve_order_ids],
);

SELECT *
FROM bronze.land_json AS lj
CROSS JOIN json_array_elements(lj.response) WITH ORDINALITY AS kv_json
;


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\cli\main.py", line 95, in cli
    context = Context(
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\context.py", line 296, in __init__
    self.load()
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\context.py", line 406, in load
    project = self._loader.load(self, update_schemas)
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 131, in load
    models = self._load_models(macros, jinja_macros)
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 274, in _load_models
    models = self._load_sql_models(macros, jinja_macros)
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 318, in _load_sql_models
    model = cache.get_or_load_model(path, _load)
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 439, in get_or_load_model
    model = self._model_cache.get_or_load(
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\model\cache.py", line 52, in get_or_load
    loaded_model = loader()
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 301, in _load
    raise ConfigError(
sqlmesh.utils.errors.ConfigError: Failed to parse a model definition at 'C:\Git\transformer\sqlmesh\test\models\test.sql': Invalid expression / Unexpected token. Line 11, Col: 48.
  ve_order_ids],
);

SELECT *
FROM bronze.land_json AS lj
CROSS JOIN json_array_elements(lj.response) WITH ORDINALITY AS kv_json
;
.
2023-10-26 08:38:27,061 - sqlmesh.cli - ERROR - Unhandled exception (__init__.py:45)
Traceback (most recent call last):
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 297, in _load
    expressions = parse(
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\dialect.py", line 650, in parse
    for expression in parser.parse(chunk, sql):
  File "C:\Git\transformer\.venv\lib\site-packages\sqlglot\parser.py", line 985, in parse
    return self._parse(
  File "C:\Git\transformer\.venv\lib\site-packages\sqlglot\parser.py", line 1054, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "C:\Git\transformer\.venv\lib\site-packages\sqlglot\parser.py", line 1095, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 11, Col: 48.
  ve_order_ids],
);

SELECT *
FROM bronze.land_json AS lj
CROSS JOIN json_array_elements(lj.response) WITH ORDINALITY AS kv_json
;


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\cli\__init__.py", line 43, in _debug_exception_handler
    return func()
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\cli\__init__.py", line 24, in <lambda>
    return handler(lambda: func(*args, **kwargs))
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\cli\main.py", line 95, in cli
    context = Context(
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\context.py", line 296, in __init__
    self.load()
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\context.py", line 406, in load
    project = self._loader.load(self, update_schemas)
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 131, in load
    models = self._load_models(macros, jinja_macros)
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 274, in _load_models
    models = self._load_sql_models(macros, jinja_macros)
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 318, in _load_sql_models
    model = cache.get_or_load_model(path, _load)
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 439, in get_or_load_model
    model = self._model_cache.get_or_load(
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\model\cache.py", line 52, in get_or_load
    loaded_model = loader()
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 301, in _load
    raise ConfigError(
sqlmesh.utils.errors.ConfigError: Failed to parse a model definition at 'C:\Git\transformer\sqlmesh\test\models\test.sql': Invalid expression / Unexpected token. Line 11, Col: 48.
  ve_order_ids],
);

SELECT *
FROM bronze.land_json AS lj
CROSS JOIN json_array_elements(lj.response) WITH ORDINALITY AS kv_json
;
.
Traceback (most recent call last):
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 297, in _load
    expressions = parse(
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\dialect.py", line 650, in parse
    for expression in parser.parse(chunk, sql):
  File "C:\Git\transformer\.venv\lib\site-packages\sqlglot\parser.py", line 985, in parse
    return self._parse(
  File "C:\Git\transformer\.venv\lib\site-packages\sqlglot\parser.py", line 1054, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "C:\Git\transformer\.venv\lib\site-packages\sqlglot\parser.py", line 1095, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 11, Col: 48.
  ve_order_ids],
);

SELECT *
FROM bronze.land_json AS lj
CROSS JOIN json_array_elements(lj.response) WITH ORDINALITY AS kv_json
;


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\deschman\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\deschman\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Git\transformer\.venv\Scripts\sqlmesh.exe\__main__.py", line 7, in <module>
  File "C:\Git\transformer\.venv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Git\transformer\.venv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Git\transformer\.venv\lib\site-packages\click\core.py", line 1656, in invoke
    super().invoke(ctx)
  File "C:\Git\transformer\.venv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Git\transformer\.venv\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Git\transformer\.venv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\cli\__init__.py", line 24, in wrapper
    return handler(lambda: func(*args, **kwargs))
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\cli\__init__.py", line 43, in _debug_exception_handler
    return func()
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\cli\__init__.py", line 24, in <lambda>
    return handler(lambda: func(*args, **kwargs))
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\cli\main.py", line 95, in cli
    context = Context(
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\context.py", line 296, in __init__
    self.load()
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\context.py", line 406, in load
    project = self._loader.load(self, update_schemas)
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 131, in load
    models = self._load_models(macros, jinja_macros)
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 274, in _load_models
    models = self._load_sql_models(macros, jinja_macros)
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 318, in _load_sql_models
    model = cache.get_or_load_model(path, _load)
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 439, in get_or_load_model
    model = self._model_cache.get_or_load(
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\model\cache.py", line 52, in get_or_load
    loaded_model = loader()
  File "C:\Git\transformer\.venv\lib\site-packages\sqlmesh\core\loader.py", line 301, in _load
    raise ConfigError(
sqlmesh.utils.errors.ConfigError: Failed to parse a model definition at 'C:\Git\transformer\sqlmesh\test\models\test.sql': Invalid expression / Unexpected token. Line 11, Col: 48.
  ve_order_ids],
);

SELECT *
FROM bronze.land_json AS lj
CROSS JOIN json_array_elements(lj.response) WITH ORDINALITY AS kv_json
;
.
```

I have confirmed that this query runs as expected in my local postgres database via my sql editor and would expect sqlmesh to recognize the token and pass it through to the database.

**Comment by GeorgeSittas** [comment]
Thanks @deschman, I'll take a look. It looks like SQLGlot doesn't support the ordinality clause for that function right now.
