### ISSUE TITLE
MSSQL error: An expression of non-boolean type specified in a context where a condition is expected, near

### ISSUE THREAD

**Issue by JonasDavisFondene** [TobikoData/sqlmesh#1682]
**Versions**
sqlmesh version
0.48.0

python version
3.11

SQL Server Management Studio v18.6
SQL Server Management Studio						15.0.18338.0
SQL Server Management Objects (SMO)						16.100.41011.9
Microsoft Analysis Services Client Tools						15.0.19205.0
Microsoft Data Access Components (MDAC)						10.0.19041.3570
Microsoft MSXML						3.0 6.0 
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.19045

**destination**
mssql

**Describe the problem**
"sqlmesh run" and "slqmesh plan dev" results in an error "An expression of non-boolean type specified in a context where a condition is expected, near" on mssql.

The error seems to be due to the sql statement being called from
https://github.com/TobikoData/sqlmesh/blob/main/sqlmesh/core/engine_adapter/base.py#L1352:
<pre>
SELECT "id", "intervals"."name", "intervals"."identifier", "version", "start_ts", "end_ts", "is_dev", "is_removed" 
FROM "sqlmesh"."_intervals" AS "intervals" JOIN (
	SELECT DISTINCT "name", "identifier" FROM "sqlmesh"."_intervals" AS "intervals" WHERE NOT "is_compacted"
) AS "uncompacted" 
ON "intervals"."name" = "uncompacted"."name" 
AND "intervals"."identifier" = "uncompacted"."identifier" 
ORDER BY "intervals"."name", "intervals"."identifier", "created_ts", "is_removed";
</pre>

It assumes that the "is_compacted" column can be evalulated like a boolean in itself, but that seems to be illegal in tsql. The correct tsql would be something like:
<pre>
SELECT "id", "intervals"."name", "intervals"."identifier", "version", "start_ts", "end_ts", "is_dev", "is_removed" 
FROM "sqlmesh"."_intervals" AS "intervals" JOIN (
	SELECT DISTINCT "name", "identifier" FROM "sqlmesh"."_intervals" AS "intervals" WHERE "is_compacted" != 1
) AS "uncompacted" 
ON "intervals"."name" = "uncompacted"."name" 
AND "intervals"."identifier" = "uncompacted"."identifier" 
ORDER BY "intervals"."name", "intervals"."identifier", "created_ts", "is_removed";
</pre>

The faulty where statement is specified here:
https://github.com/TobikoData/sqlmesh/blob/main/sqlmesh/core/state_sync/engine_adapter.py#L670

There is a similar where statement causing same error here:
https://github.com/TobikoData/sqlmesh/blob/main/sqlmesh/core/state_sync/engine_adapter.py#L624

A fix could be to replace .not() with .eq(0) or .neq(1) everywhere a boolean is evaluated like that.
I'm not sure how many of these are spread around the codebase and I haven't read sqlglot docs yet, so I'm not to say whether a better fix is instructing sqlglot, when the dialect is tsql, to parse the `where(exp.to_column("column_name").not_()` to something that would work in tsql instead of manually changing the where expression everywhere.

**Project structure**
<pre>
.venv (poetry virtual env)
pyproject.toml
src
└── sqlmesh_test:
        └── config.yaml
        └── schema.yaml
        └── Audits
        └── Seeds
        └── Tests
        └── Macros:
                ├── __init__.py
        └── Models:
                ├── clients.sql
</pre>

**Sql server test_table**
<pre>
CREATE TABLE
    datafoundations.dev_jda.test_table
    ( test_column [int] );

insert into datafoundations.dev_jda.test_table
values (1);
</pre>

**file contents**
clients.sql
<pre>
MODEL (
  name portman.test_table,
  kind VIEW
);

SELECT
  *
FROM dev_jda.test_table
</pre>

config.yaml
<pre>
gateways:
    database:
        connection:
            type: mssql
            user: {{ env_var('DESTINATION__MSSQL__CREDENTIALS__USERNAME') }}
            password: {{ env_var('DESTINATION__MSSQL__CREDENTIALS__PASSWORD') }}
            host: "172.20.0.9"
            port: 1435
            database: datafoundations
            timeout: 60

default_gateway: database

model_defaults:
    dialect: tsql
</pre>

schema.yaml
<pre>
- name: dev_jda.test_table
  columns:
    test_column: INTEGER
</pre>

**Full error flow message:**
<pre>
$ poetry run sqlmesh plan
======================================================================
Successfully Ran 0 tests against duckdb
----------------------------------------------------------------------
New environment `prod` will be created from `prod`
Summary of differences against `prod`:

Models:
└── Added:
    ├── portman.test_table
    └── dev_jda.test_table
Models needing backfill (missing dates):       
└── portman.test_table: 2023-11-08 - 2023-11-08

Apply - Backfill Tables [y/n]: y
Creating new model versions ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0% • 2/2 • 0:00:00

All model versions have been created successfully

[1/1] portman.test_table finished in 0.27s
Evaluating models ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0% • 1/1 • 0:00:00

All model batches have been executed successfully

Virtually Updating 'prod' ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0% • 0:00:00

The target environment has been updated successfully

~/repositories/sqlmesh-test2/src/sqlmesh_test
$ poetry run sqlmesh run
Traceback (most recent call last):
  File "src\\pymssql\\_pymssql.pyx", line 459, in pymssql._pymssql.Cursor.execute
  File "src\\pymssql\\_mssql.pyx", line 1087, in pymssql._mssql.MSSQLConnection.execute_query
  File "src\\pymssql\\_mssql.pyx", line 1118, in pymssql._mssql.MSSQLConnection.execute_query
  File "src\\pymssql\\_mssql.pyx", line 1251, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src\\pymssql\\_mssql.pyx", line 1789, in pymssql._mssql.check_cancel_and_raise
  File "src\\pymssql\\_mssql.pyx", line 1835, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (4145, b"An expression of non-boolean type specified in a context where a condition is expected, near ')'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Scripts\sqlmesh.exe\__main__.py", line 7, in <module>
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\cli\__init__.py", line 24, in wrapper
    return handler(lambda: func(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\cli\__init__.py", line 33, in _default_exception_handler
    return func()
           ^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\cli\__init__.py", line 24, in <lambda>
    return handler(lambda: func(*args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\cli\main.py", line 325, in run
    success = context.run(environment, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\core\context.py", line 461, in run
    self._run_janitor()
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\core\context.py", line 1416, in _run_janitor
    self.state_sync.compact_intervals()
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\core\state_sync\base.py", line 405, in delegate
    return getattr(self.state_sync, name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\core\state_sync\common.py", line 81, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\core\state_sync\engine_adapter.py", line 585, in compact_intervals
    interval_ids, snapshot_intervals = self._get_snapshot_intervals(uncompacted_only=True)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\core\state_sync\engine_adapter.py", line 689, in _get_snapshot_intervals
    rows = self.engine_adapter.fetchall(query.where(where), quote_identifiers=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 1253, in fetchall
    self.execute(
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 1350, in execute
    self.cursor.execute(sql, **kwargs)
  File "src\\pymssql\\_pymssql.pyx", line 479, in pymssql._pymssql.Cursor.execute
pymssql._pymssql.OperationalError: (4145, b"An expression of non-boolean type specified in a context where a condition is expected, near ')'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")

~/repositories/sqlmesh-test2/src/sqlmesh_test
$ poetry run sqlmesh plan dev
======================================================================
Successfully Ran 0 tests against duckdb
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src\\pymssql\\_pymssql.pyx", line 459, in pymssql._pymssql.Cursor.execute
  File "src\\pymssql\\_mssql.pyx", line 1087, in pymssql._mssql.MSSQLConnection.execute_query
  File "src\\pymssql\\_mssql.pyx", line 1118, in pymssql._mssql.MSSQLConnection.execute_query
  File "src\\pymssql\\_mssql.pyx", line 1251, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src\\pymssql\\_mssql.pyx", line 1789, in pymssql._mssql.check_cancel_and_raise
  File "src\\pymssql\\_mssql.pyx", line 1835, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (4145, b"An expression of non-boolean type specified in a context where a condition is expected, near ';'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Scripts\sqlmesh.exe\__main__.py", line 7, in <module>
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\cli\__init__.py", line 24, in wrapper
    return handler(lambda: func(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\cli\__init__.py", line 33, in _default_exception_handler
    return func()
           ^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\cli\__init__.py", line 24, in <lambda>
    return handler(lambda: func(*args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\cli\main.py", line 307, in plan
    context.plan(environment, restate_models=restate_models, select_models=select_models, **kwargs)
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\core\context.py", line 868, in plan
    default_end = self.state_sync.max_interval_end_for_environment(c.PROD) if is_dev else None
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\core\state_sync\base.py", line 405, in delegate
    return getattr(self.state_sync, name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\core\state_sync\engine_adapter.py", line 616, in max_interval_end_for_environment
    end = self.engine_adapter.fetchone(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 1239, in fetchone
    self.execute(
  File "C:\Users\jda.fon\repositories\sqlmesh-test2\.venv\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 1350, in execute
    self.cursor.execute(sql, **kwargs)
  File "src\\pymssql\\_pymssql.pyx", line 479, in pymssql._pymssql.Cursor.execute
pymssql._pymssql.OperationalError: (4145, b"An expression of non-boolean type specified in a context where a condition is expected, near ';'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")
</pre>

**Comment by georgesittas** [comment]
@JonasDavisFondene I've implemented a temporary workaround in https://github.com/tobymao/sqlglot/commit/5c750f30896c665b7ea80db0c671af723b39cc93 to unblock you.

Can you upgrade SQLGlot to v19.1.2 (`pip install sqlglot --upgrade`) and try again? Let us know if you encounter any other issues.

**Comment by JonasDavisFondene** [comment]
> The faulty where statement is specified here: https://github.com/TobikoData/sqlmesh/blob/main/sqlmesh/core/state_sync/engine_adapter.py#L670
> 
> There is a similar where statement causing same error here: https://github.com/TobikoData/sqlmesh/blob/main/sqlmesh/core/state_sync/engine_adapter.py#L624

I had a local version of the engine_adapter.py that handled the two .where() lines, that seemed to work.
After updating to latest sqlmesh with sqlglot=19.2.0 I can confirm that I can do sqlmesh run and sqlmesh plan dev without any errors.

Thank you for such a quick response and package update, that is just amazing! :)
