### ISSUE TITLE
Parenthesis wrapping the last statement in SQL is valid but not supported

### ISSUE THREAD

**Issue by github-christophe-oudar** [TobikoData/sqlmesh#2137]
If a query looks like:
```
WITH base AS (SELECT 1)
(SELECT 1)
```
it may run (it's valid on BigQuery) but it fails with following stacktrace:
```
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/dbt-1.7/lib/python3.11/site-packages/web/server/api/endpoints/plan.py", line 91, in get_plan_builder
    plan_builder = context.plan_builder(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/dbt-1.7/lib/python3.11/site-packages/sqlmesh/core/context.py", line 974, in plan_builder
    snapshots = self._snapshots(models_override)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/dbt-1.7/lib/python3.11/site-packages/sqlmesh/core/context.py", line 1650, in _snapshots
    snapshots = _nodes_to_snapshots(nodes)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/dbt-1.7/lib/python3.11/site-packages/sqlmesh/core/context.py", line 1640, in _nodes_to_snapshots
    snapshot = Snapshot.from_node(
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/dbt-1.7/lib/python3.11/site-packages/sqlmesh/core/snapshot/definition.py", line 570, in from_node
    fingerprint=fingerprint_from_node(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/dbt-1.7/lib/python3.11/site-packages/sqlmesh/core/snapshot/definition.py", line 1291, in fingerprint_from_node
    for table in node.depends_on
                 ^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/dbt-1.7/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/dbt-1.7/lib/python3.11/site-packages/sqlmesh/core/audit/definition.py", line 309, in depends_on
    query = self.render_query(self)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/dbt-1.7/lib/python3.11/site-packages/sqlmesh/core/audit/definition.py", line 111, in render_query
    rendered_query = query_renderer.render(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/dbt-1.7/lib/python3.11/site-packages/sqlmesh/core/renderer.py", line 431, in render
    raise_config_error(f"Query needs to be a SELECT or a UNION {query}.", self._path)
  File "/opt/homebrew/anaconda3/envs/dbt-1.7/lib/python3.11/site-packages/sqlmesh/utils/errors.py", line 133, in raise_config_error
    raise error_type(f"{msg} at '{location}'")
sqlmesh.utils.errors.ConfigError: Query needs to be a SELECT or a UNION
```

*Workaround*
Remove the wrapping (as unecessary), eg
```
WITH base AS (SELECT 1)
SELECT 1
```

**Comment by georgesittas** [comment]
@tobymao maybe we should change the `Subqueryable`s throughout the codebase into `Unionable`s? The latter is a superset of the former and also covers subqueries (and udtfs, though these are probably irrelevant to this discussion).
