### ISSUE TITLE
airflow - sqlmesh plan -> [Errno 13] Permission denied: '.cache' 

### ISSUE THREAD

**Issue by sudokai** [TobikoData/sqlmesh#2785]
When you apply a plan with the sqlmesh/airflow integration, you get an `[Errno 13] Permission denied: '.cache'` when there are already snapshots in the `_snapshots` table and it attemps to load the snapshot and needs to create the `.cache` dir.

Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/pathlib.py", line 1117, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '.cache/model_definition'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/airflow/lib/python3.11/site-packages/sqlmesh/schedulers/airflow/api.py", line 45, in apply_plan
    spec = create_plan_dag_spec(plan, state_sync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/lib/python3.11/site-packages/sqlmesh/schedulers/airflow/plan.py", line 87, in create_plan_dag_spec
    stored_snapshots = state_sync.get_snapshots([*new_snapshots, *request.environment.snapshots])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/lib/python3.11/site-packages/sqlmesh/core/state_sync/cache.py", line 76, in get_snapshots
    existing.update(self.state_sync.get_snapshots(missing))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/lib/python3.11/site-packages/sqlmesh/core/state_sync/common.py", line 94, in get_snapshots
    return self._get_snapshots(snapshot_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/lib/python3.11/site-packages/sqlmesh/core/state_sync/engine_adapter.py", line 476, in _get_snapshots
    snapshot = parse_snapshot(
               ^^^^^^^^^^^^^^^
  File "/usr/local/airflow/lib/python3.11/site-packages/sqlmesh/core/state_sync/engine_adapter.py", line 1423, in parse_snapshot
    payload["node"] = model_cache.get_or_load(f"{name}_{identifier}", loader=loader)  # type: ignore
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/lib/python3.11/site-packages/sqlmesh/core/model/cache.py", line 57, in get_or_load
    self._file_cache.put(name, entry_id, value=new_entry)
  File "/usr/local/airflow/lib/python3.11/site-packages/sqlmesh/utils/cache.py", line 117, in put
    self._path.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.11/pathlib.py", line 1121, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.11/pathlib.py", line 1117, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '.cache'
```

I traced the problem and for some reason, it tries to create the `.cache` under the root folder `/` on the airflow server, even though all the airflow processes run under the `airflow` linux user which has a home directory `/usr/local/airflow`

Debian 12.2, Airflow 2.8.4, sqlmesh 0.104.1

Airflow installed with virtualenv python 3.11

apache-airflow[postgres,google,statsd,virtualenv,ssh]==2.8.4
sqlmesh[bigquery]==0.104.1

**Comment by izeigerman** [comment]
I believe this happens because the working directory of the Airflow process is set to `/root` for some reason and not something more reasonable like a home folder of the `airflow` user. @sudokai any chance you can confirm the work dir for the Airflow scheduler process?

**Comment by sudokai** [comment]
You're right! Since our airflow instance is run by systemd, the working directory defaulted to `/` even though the home dir of the user was not '/'. Thanks for looking into this, I will close the issue.
