### ISSUE TITLE
ibis sql bug

### ISSUE THREAD

**Issue by wleescor** [TobikoData/sqlmesh#2894]
I'm trying to the ibis sql example: https://github.com/TobikoData/sqlmesh/blob/main/examples/ibis/models/ibis_full_model_sql.py
and I've added in a string concatenation which doesn't seem to work.
  test=incremental_model.mutate(test=_['ds'] +_['ds']) 
```
import ibis
from ibis.expr.operations import Namespace, UnboundTable
from sqlmesh.core.macros import MacroEvaluator
from sqlmesh.core.model import model


@model(
    'sqlmesh_example.ibis_full_model_sql',
    is_sql=True,
    dialect='tsql',
    kind='FULL',
    audits=['assert_positive_order_ids'],
    description='This model uses ibis to generate and return a SQL string',
)
def entrypoint(evaluator: MacroEvaluator) -> str:  # noqa: ARG001
    """Create model that uses ibis to generate and return a SQL string."""
    from ibis import _
    # create table reference
    incremental_model = UnboundTable(
        name='incremental_model',
        schema={'id': 'int32', 'item_id': 'int32', 'ds': 'varchar'},
        namespace=Namespace(catalog='sqlmesh_example'),
    ).to_expr()

    # build query
    count = incremental_model.id.nunique()
    aggregate = incremental_model.group_by('item_id').aggregate(num_orders=count)
    query = aggregate  # .order_by("item_id")
    test=incremental_model.mutate(test=_['ds']+_['ds'])
    return ibis.to_sql(test)
```

The error message is very cryptic, but essentially ```b"Incorrect syntax near '|```
I am ussing mssql connection
```
Traceback (most recent call last):
  File "src\\pymssql\\_pymssql.pyx", line 447, in pymssql._pymssql.Cursor.execute
  File "src\\pymssql\\_mssql.pyx", line 1125, in pymssql._mssql.MSSQLConnection.execute_query
  File "src\\pymssql\\_mssql.pyx", line 1156, in pymssql._mssql.MSSQLConnection.execute_query
  File "src\\pymssql\\_mssql.pyx", line 1289, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src\\pymssql\\_mssql.pyx", line 1852, in pymssql._mssql.check_cancel_and_raise
  File "src\\pymssql\\_mssql.pyx", line 1898, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (102, b"Incorrect syntax near '|'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".venv\lib\site-packages\pandas\io\sql.py", line 2262, in execute
    cur.execute(sql, *args)
  File "src\\pymssql\\_pymssql.pyx", line 462, in pymssql._pymssql.Cursor.execute
pymssql.exceptions.ProgrammingError: (102, b"Incorrect syntax near '|'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".venv\lib\site-packages\web\server\api\endpoints\commands.py", line 69, in evaluate
    df = context.evaluate(
  File ".venv\lib\site-packages\sqlmesh\core\analytics\__init__.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "venv\lib\site-packages\sqlmesh\core\context.py", line 802, in evaluate
    df = self.snapshot_evaluator.evaluate_and_fetch(
  File ".venv\lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 164, in evaluate_and_fetch
    result = self._evaluate_snapshot(
  File ".venv\lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 578, in _evaluate_snapshot
    return self.adapter._fetch_native_df(query_or_df.limit(limit))
  File ".venv\lib\site-packages\sqlmesh\core\engine_adapter\mixins.py", line 70, in _fetch_native_df
    df = read_sql_query(sql, self._connection_pool.get())
  File ".venv\lib\site-packages\pandas\io\sql.py", line 486, in read_sql_query
    return pandas_sql.read_query(
  File ".venv\lib\site-packages\pandas\io\sql.py", line 2326, in read_query
    cursor = self.execute(sql, params)
  File ".venv\lib\site-packages\pandas\io\sql.py", line 2274, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql 'SELECT TOP 1000 [t0].[id] AS [id], [t0].[item_id] AS [item_id], [t0].[ds] AS [ds], [t0].[ds] || [t0].[ds] AS [test] FROM [ausdashboards].[sqlmesh__sqlmesh_example].[sqlmesh_example__incremental_model__1055806947] AS [t0];': (102, b"Incorrect syntax near '|'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")
```

**Comment by tobymao** [comment]
@wleescor i think you need to specify the dialect in to_sql() to the dialect of your model / engine, otherwise the sql is output in sqlglot generic dialect.

**Comment by wleescor** [comment]
hmm looks like there's an error in the ibis sql example. there is no column "ds": "varchar". The seed only has id, item_id and event_date

**Comment by tobymao** [comment]
what are you referring to? the seed looks like it has a ds 

https://github.com/TobikoData/sqlmesh/blob/main/examples/ibis/models/seed_model.sql

**Comment by wleescor** [comment]
https://github.com/TobikoData/sqlmesh-examples/blob/main/002_ibis/models/seed_model.sql

**Comment by tobymao** [comment]
looks like that's a different repo, and it's out of date

**Comment by tobymao** [comment]
i'm going to close this for now as it seems to be an ibis generation issue
