### ISSUE TITLE
Refreshing snapshot intervals is not supported by the Airflow state sync.

### ISSUE THREAD

**Issue by jpgianfaldoni** [TobikoData/sqlmesh#2971]
Im trying to use integrate Airflow with SQLMesh but keep getting this error every time i try to generate a Plan:

```
general
2024-07-30 17:05:29
Unable to get plan backfills

Version: 0.115.1
Type: <class 'NotImplementedError'>
Origin: API -> plan -> run_plan
Refreshing snapshot intervals is not supported by the Airflow state sync.
```

Full traceback:

```
Traceback (most recent call last):
  File "/Users/joaoandrade/Documents/SQLMesh/.env/lib/python3.12/site-packages/web/server/api/endpoints/plan.py", line 231, in _get_plan_builder
    _get_plan_backfills(context, plan),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joaoandrade/Documents/SQLMesh/.env/lib/python3.12/site-packages/web/server/api/endpoints/plan.py", line 134, in _get_plan_backfills
    batches = context.scheduler().batches()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joaoandrade/Documents/SQLMesh/.env/lib/python3.12/site-packages/sqlmesh/core/scheduler.py", line 161, in batches
    self.state_sync.refresh_snapshot_intervals(snapshots)
  File "/Users/joaoandrade/Documents/SQLMesh/.env/lib/python3.12/site-packages/sqlmesh/core/state_sync/base.py", line 463, in delegate
    return getattr(self.state_sync, name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joaoandrade/Documents/SQLMesh/.env/lib/python3.12/site-packages/sqlmesh/schedulers/airflow/state_sync.py", line 252, in refresh_snapshot_intervals
    raise NotImplementedError(
NotImplementedError: Refreshing snapshot intervals is not supported by the Airflow state sync.
```

For more context, this is the only model i`ve created:

```
MODEL (
  name sales_test,
  kind FULL
);

SELECT
  *
FROM sales_db.sales.journey
LIMIT 1
```

And this is my config.yaml with sensitive info removed:
```
gateways:
  my_gateway:
    connection:
      type: trino
      user: usernam
      method: basic
      password: password
      host: host
      port: 443   
      catalog : catalog
    state_connection:
      type: duckdb
      database: state.db
default_scheduler:
  type: airflow
  airflow_url: http://localhost:8080/
  username: username 
  password: password
model_defaults:
  dialect: trino
  start: 2024-07-22
```

Aditional info: 
- The trino connection works and im able to make queries using the UI
- The sqlmesh_janitor_dag DAG was created and works aswell

**Comment by erindru** [comment]
Hi @jpgianfaldoni , it looks like you're using duckdb as the `state_connection` which isnt supported with Airflow.

When using Airflow you have two options for state:
 - Use the [Airflow database](https://sqlmesh.readthedocs.io/en/stable/integrations/airflow/)
 - [Configure a connection in Airflow](https://sqlmesh.readthedocs.io/en/stable/integrations/airflow/#state-connection) to point to your state database (which would need to be supported by Airflow and this means it should be network accessible, we [recommend Postgres](https://sqlmesh.readthedocs.io/en/stable/guides/configuration/#state-connection))

So you'll need to remove the `state_connection` from your gateway config and choose one of these options

**Comment by jpgianfaldoni** [comment]
Thank you very much, will try to do that!
