### ISSUE TITLE
SQLMesh+dbt+duckdb: Unable to read source declared in dbt

### ISSUE THREAD

**Issue by cnstlungu** [TobikoData/sqlmesh#2988]
I'm using sqlmesh+dbt+duckdb. I have declared my sources as follows:

![image](https://github.com/user-attachments/assets/03ed0a7b-8d43-4c60-8f86-99788103d1d0)

In my model, upon using the source jinja function, I get an error:

![image](https://github.com/user-attachments/assets/e5dc8423-c9ee-4d41-a1e0-030b495c4998)

```
Traceback (most recent call last):
  File "/home/costin/repos/portable-data-stack-sqlmesh/.venv/lib/python3.10/site-packages/web/server/api/endpoints/commands.py", line 69, in evaluate
    df = context.evaluate(
  File "/home/costin/repos/portable-data-stack-sqlmesh/.venv/lib/python3.10/site-packages/sqlmesh/core/analytics/__init__.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/costin/repos/portable-data-stack-sqlmesh/.venv/lib/python3.10/site-packages/sqlmesh/core/context.py", line 802, in evaluate
    df = self.snapshot_evaluator.evaluate_and_fetch(
  File "/home/costin/repos/portable-data-stack-sqlmesh/.venv/lib/python3.10/site-packages/sqlmesh/core/snapshot/evaluator.py", line 164, in evaluate_and_fetch
    result = self._evaluate_snapshot(
  File "/home/costin/repos/portable-data-stack-sqlmesh/.venv/lib/python3.10/site-packages/sqlmesh/core/snapshot/evaluator.py", line 578, in _evaluate_snapshot
    return self.adapter._fetch_native_df(query_or_df.limit(limit))
  File "/home/costin/repos/portable-data-stack-sqlmesh/.venv/lib/python3.10/site-packages/sqlmesh/core/engine_adapter/base.py", line 1697, in _fetch_native_df
    self.execute(query, quote_identifiers=quote_identifiers)
  File "/home/costin/repos/portable-data-stack-sqlmesh/.venv/lib/python3.10/site-packages/sqlmesh/core/engine_adapter/base.py", line 1831, in execute
    self._execute(sql, **kwargs)
  File "/home/costin/repos/portable-data-stack-sqlmesh/.venv/lib/python3.10/site-packages/sqlmesh/core/engine_adapter/base.py", line 1837, in _execute
    self.cursor.execute(sql, **kwargs)
duckdb.duckdb.CatalogException: Catalog Error: Table with name channels does not exist!
Did you mean "postcard_company_raw.raw_channels"?
LINE 1: ...T_TIMESTAMP AS "loaded_timestamp" FROM "datamart"."parquet_input"."channels" A...
                                                  ^
```

![image](https://github.com/user-attachments/assets/01e55b55-6306-4998-93de-1c776cb0976d)

It is to be pointed out that the `parquet_input` is just a source name, not a database schema/dataset as indicated above. Also, this does work if I use the read_parquet directly

![image](https://github.com/user-attachments/assets/68cff871-97d9-4a94-98ea-7ea95c460edd)

My environment:
```
duckdb==1.0.0
dbt-duckdb==1.8.1
sqlmesh==0.104.0
pydantic==2.4.0
```

**Comment by tobymao** [comment]
@Themiscodes or @treysp can you take a look?
