### ISSUE TITLE
Capitalization of sqlmesh__* schema causes plan to fail when resolving dependencies

### ISSUE THREAD

**Issue by hmeng** [TobikoData/sqlmesh#3021]
I have a Python model that uses context.table to dynamically generate dependencies. In Snowflake, this leads to a schema not found error because the sqlmesh__* schemas are queried as "DB_TEST"."SQLMESH__*"."TABLE" instead of "DB_TEST"."sqlmesh__*"."TABLE"

**Comment by tobymao** [comment]
i’m can you provide a reproducible example please

**Comment by hmeng** [comment]
If I add the following two models to my project, it produces the error:

```
import typing as t
from datetime import datetime
import pandas as pd

from sqlmesh import ExecutionContext, model
from sqlmesh.core.model.kind import ModelKindName

@model(
    "source_test.test",
    kind=dict(
        name=ModelKindName.FULL
    ),
    columns={
        "one": "int"
    }
)
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    execution_time: datetime,
    **kwargs: t.Any,
) -> pd.DataFrame:
    return pd.DataFrame({'ONE': 1}, index = [0])
```
    
```
import typing as t
from datetime import datetime
import pandas as pd

from sqlmesh import ExecutionContext, model
from sqlmesh.core.model.kind import ModelKindName

@model(
    "source_test.test2",
    kind=dict(
        name=ModelKindName.FULL
    ),
    columns={
        "one": "int"
    }
)
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    execution_time: datetime,
    **kwargs: t.Any,
) -> pd.DataFrame:
    table = context.table('source_test.test')
    return context.fetchdf(f'SELECT * FROM {table}')
```

**Comment by hmeng** [comment]
Specifically, it is returning an error from Snowflake because the table was not quoted (sqlmesh__ is in lowercase)

```
FAILED processing snapshot "DB_RESEARCH_DEV"."SOURCE_TEST"."TEST2"
Traceback (most recent call last):
  File "/Users/henrymeng/.pyenv/versions/3.9.11/lib/python3.9/site-packages/sqlmesh/core/model/definition.py", line 1413, in render
    df_or_iter = env(
  File "<string>", line 4, in execute
  File "/Users/henrymeng/.pyenv/versions/3.9.11/lib/python3.9/site-packages/sqlmesh/core/context.py", line 196, in fetchdf
    return self.engine_adapter.fetchdf(query, quote_identifiers=quote_identifiers)
  File "/Users/henrymeng/.pyenv/versions/3.9.11/lib/python3.9/site-packages/sqlmesh/core/engine_adapter/base.py", line 1786, in fetchdf
    df = self._fetch_native_df(query, quote_identifiers=quote_identifiers)
  File "/Users/henrymeng/.pyenv/versions/3.9.11/lib/python3.9/site-packages/sqlmesh/core/engine_adapter/snowflake.py", line 278, in _fetch_native_df
    self.execute(query, quote_identifiers=quote_identifiers)
  File "/Users/henrymeng/.pyenv/versions/3.9.11/lib/python3.9/site-packages/sqlmesh/core/engine_adapter/base.py", line 1913, in execute
    self._execute(sql, **kwargs)
  File "/Users/henrymeng/.pyenv/versions/3.9.11/lib/python3.9/site-packages/sqlmesh/core/engine_adapter/base.py", line 1919, in _execute
    self.cursor.execute(sql, **kwargs)
  File "/Users/henrymeng/.pyenv/versions/3.9.11/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 1087, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/Users/henrymeng/.pyenv/versions/3.9.11/lib/python3.9/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/Users/henrymeng/.pyenv/versions/3.9.11/lib/python3.9/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/Users/henrymeng/.pyenv/versions/3.9.11/lib/python3.9/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (02000): 01b674cd-0107-7b34-0007-64c30007f7e6: SQL compilation error:
Schema 'DB_RESEARCH_DEV.SQLMESH__SOURCE_TEST' does not exist or not authorized.
```

**Comment by tobymao** [comment]
This is due to the table returned by context.table not being quoted. You can work around this by doing exp.to_table(table).sql(dialect="snowflake", identify=True) for now.

We'll work on a fix.
