### ISSUE TITLE
Query optimizer cannot properly handle `IFNULL` and `COALESCE` expressions.

### ISSUE THREAD

**Issue by Ziemin** [TobikoData/sqlmesh#3080]
When switching from `sqlmesh` 0.110 to 0.119 all sqlmesh commands started failing immediately during project instantiation.
For the context, I'm using BigQuery dialect for all of my models.
I've been getting the following error:
```
Traceback (most recent call last):
  File ".venv/bin/sqlmesh", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File ".venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File ".venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlmesh/cli/__init__.py", line 31, in wrapper
    return handler(sqlmesh_context, lambda: func(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlmesh/cli/__init__.py", line 40, in _default_exception_handler
    return func()
           ^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlmesh/cli/__init__.py", line 31, in <lambda>
    return handler(sqlmesh_context, lambda: func(*args, **kwargs))
                                            ^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlmesh/cli/main.py", line 96, in cli
    context = Context(
              ^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlmesh/core/context.py", line 380, in __init__
    self.load()
  File ".venv/lib/python3.11/site-packages/sqlmesh/core/context.py", line 512, in load
    project = self._loader.load(self, update_schemas)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlmesh/core/loader.py", line 136, in load
    update_model_schemas(
  File ".venv/lib/python3.11/site-packages/sqlmesh/core/loader.py", line 63, in update_model_schemas
    optimized_query_cache.with_optimized_query(model)
  File ".venv/lib/python3.11/site-packages/sqlmesh/core/model/cache.py", line 101, in with_optimized_query
    self._put(name, model)
  File ".venv/lib/python3.11/site-packages/sqlmesh/core/model/cache.py", line 115, in _put
    optimized_query = model.render_query()
                      ^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlmesh/core/model/definition.py", line 1048, in render_query
    query = self._query_renderer.render(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlmesh/core/renderer.py", line 444, in render
    query = self._optimize_query(query, deps)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlmesh/core/renderer.py", line 497, in _optimize_query
    simplify(
  File ".venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py", line 133, in simplify
    expression = while_changing(expression, _simplify)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/helper.py", line 212, in while_changing
    expression = func(expression)
                 ^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py", line 113, in _simplify
    exp.replace_children(node, lambda e: _simplify(e, False))
  File ".venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7523, in replace_children
    for child_node in ensure_collection(fun(cn, *args, **kwargs)):
                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py", line 113, in <lambda>
    exp.replace_children(node, lambda e: _simplify(e, False))
                                         ^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py", line 113, in _simplify
    exp.replace_children(node, lambda e: _simplify(e, False))
  File ".venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7523, in replace_children
    for child_node in ensure_collection(fun(cn, *args, **kwargs)):
                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py", line 113, in <lambda>
    exp.replace_children(node, lambda e: _simplify(e, False))
                                         ^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py", line 113, in _simplify
    exp.replace_children(node, lambda e: _simplify(e, False))
  File ".venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7523, in replace_children
    for child_node in ensure_collection(fun(cn, *args, **kwargs)):
                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py", line 113, in <lambda>
    exp.replace_children(node, lambda e: _simplify(e, False))
                                         ^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py", line 113, in _simplify
    exp.replace_children(node, lambda e: _simplify(e, False))
  File ".venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7523, in replace_children
    for child_node in ensure_collection(fun(cn, *args, **kwargs)):
                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py", line 113, in <lambda>
    exp.replace_children(node, lambda e: _simplify(e, False))
                                         ^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py", line 113, in _simplify
    exp.replace_children(node, lambda e: _simplify(e, False))
  File ".venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7523, in replace_children
    for child_node in ensure_collection(fun(cn, *args, **kwargs)):
                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py", line 113, in <lambda>
    exp.replace_children(node, lambda e: _simplify(e, False))
                                         ^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py", line 113, in _simplify
    exp.replace_children(node, lambda e: _simplify(e, False))
  File ".venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7523, in replace_children
    for child_node in ensure_collection(fun(cn, *args, **kwargs)):
                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py", line 113, in <lambda>
    exp.replace_children(node, lambda e: _simplify(e, False))
                                         ^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py", line 120, in _simplify
    node = simplify_coalesce(node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py", line 798, in simplify_coalesce
    for arg_index, arg in enumerate(coalesce.expressions):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 854, in __iter__
    raise TypeError(f"'{self.__class__.__name__}' object is not iterable")
TypeError: 'Literal' object is not iterable
```

The expression which triggered the exception was the following:

```
> .venv/lib/python3.11/site-packages/sqlglot/optimizer/simplify.py(798)simplify_coalesce()
-> for arg_index, arg in enumerate(coalesce.expressions):
(Pdb) coalesce
Coalesce(
  this=Column(
    this=Identifier(this=purchased, quoted=True),
    table=Identifier(this=source, quoted=True),
    _type=DataType(this=Type.INT)),
  expressions=Literal(this=0, is_string=False, _type=DataType(this=Type.INT)),
  _type=DataType(this=Type.INT))
```

After some investigation I found out it corresponded to the sql which looked like this
```sql
     ...
      IFNULL(some_indicator, 0),
     ...
```
The pattern above is prevalent in my codebase. I changed `IFNULLs` to equivalent `COALESCE` expressions to avoid this issue, but unfortunately most models were still failing with exactly the same error, that is, `expressions` attribute of `Coalesce` object was a `Literal` instead of a list.

**Comment by georgesittas** [comment]
Hey, thanks for reporting and apologies for the inconvenience. We'll take a look and get a fix in asap.

**Comment by georgesittas** [comment]
FYI the fix for this has been merged - current SQLMesh main contains it.
