### ISSUE TITLE
Parsing Failure When Populating Query Cache Doesn't Output Affected Model

### ISSUE THREAD

**Issue by eakmanrq** [TobikoData/sqlmesh#3123]
An error would look something like this:
```
Traceback (most recent call last):
  File "/Users/.../lib/python3.11/concurrent/futures/process.py", line 256, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../lib/python3.11/site-packages/sqlmesh/core/model/cache.py", line 165, in load_optimized_query_cache
    entry_name = _optimized_query_cache.put(model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../lib/python3.11/site-packages/sqlmesh/core/model/cache.py", line 119, in put
    self._put(name, model)
  File "/Users/.../lib/python3.11/site-packages/sqlmesh/core/model/cache.py", line 123, in _put
    optimized_query = model.render_query()
                      ^^^^^^^^^^^^^^^^^^^^
```

And then end with:

```
  File "/Users/.../lib/python3.11/site-packages/sqlglot/expressions.py", line 4774, in interval
    unit=self.unit.copy(),
         ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'copy'
```

It doesn't output the model name that had the error. Therefore it is hard for the user to know what model needs to be fixed.

**Comment by eakmanrq** [comment]
This might be a regression related to the new multiprocessor for populating cache but not sure.

**Comment by tobymao** [comment]
https://github.com/tobymao/sqlglot/commit/06c76f7471cdb679a7a7a35064204d94841fd929

**Comment by izeigerman** [comment]
@tobymao I think the problem here is that we don't return a model name / path on error.
