### ISSUE TITLE
PySpark with External Model (Separate Database)

### ISSUE THREAD

**Issue by wahmedswl** [TobikoData/sqlmesh#3179]
Hi!

I am using PySpark with External model which connects to separate database so I am using Python models for that. This is returning PySpark DataFrame but I am getting 

```
FAILED processing snapshot "postgres"."medallion"."bl_providers"
Traceback (most recent call last):
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/utils/concurrency.py", line 69, in _process_node
    self.fn(node)
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/scheduler.py", line 423, in evaluate_node
    self.evaluate(snapshot, start, end, execution_time, deployability_index, batch_idx)
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/scheduler.py", line 237, in evaluate
    wap_id = self.snapshot_evaluator.evaluate(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/snapshot/evaluator.py", line 126, in evaluate
    result = self._evaluate_snapshot(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/snapshot/evaluator.py", line 617, in _evaluate_snapshot
    apply(query_or_df, index)
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/snapshot/evaluator.py", line 518, in apply
    evaluation_strategy.insert(
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/snapshot/evaluator.py", line 1343, in insert
    self._replace_query_for_model(model, table_name, query_or_df)
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/snapshot/evaluator.py", line 1051, in _replace_query_for_model
    self.adapter.replace_query(
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/engine_adapter/shared.py", line 321, in internal_wrapper
    return func(*list_args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/engine_adapter/base.py", line 323, in replace_query
    source_queries, columns_to_types = self._get_source_queries_and_columns_to_types(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/engine_adapter/base.py", line 246, in _get_source_queries_and_columns_to_types
    self._get_source_queries(
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/engine_adapter/base.py", line 208, in _get_source_queries
    return self._df_to_source_queries(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/engine_adapter/base.py", line 219, in _df_to_source_queries
    assert isinstance(df, pd.DataFrame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-09-25 23:19:05,150 - MainThread - sqlmesh.core.context - ERROR - Apply Failure: Traceback (most recent call last):
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/context.py", line 1269, in apply
    self._apply(plan, circuit_breaker)
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/context.py", line 1847, in _apply
    self._scheduler.create_plan_evaluator(self).evaluate(
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/plan/evaluator.py", line 118, in evaluate
    self._backfill(
  File "/home/wahmed/medallion-sqlmesh/.venv/lib/python3.12/site-packages/sqlmesh/core/plan/evaluator.py", line 181, in _backfill
    raise SQLMeshError("Plan application failed.")
sqlmesh.utils.errors.SQLMeshError: Plan application failed.
 (context.py:1277)
```

It seems like I need to convert/return the panda DataFrame. So, PySpark DataFrame not supported in Python models?

Thanks

**Comment by tobymao** [comment]
pyspark is supported if you're using the pyspark engine. it looks like you may be using postgres? if you're using postgres, then you'll need to use pandas because there's not pyspark session

**Comment by wahmedswl** [comment]
@tobymao yes, main engine/gateway is postgres. This is external model and i am pulling data via pyspark in python model.

**Comment by wahmedswl** [comment]
@tobymao This is how i am doing it right now

![image](https://github.com/user-attachments/assets/e78b2cb0-9314-43f2-8820-48584c480413)

Thanks

**Comment by tobymao** [comment]
if you’re gateway is postgres, you can’t connect to it from pyspark, so in that instance you’d need to use pandas. if you’re gateway was spark, you’d be able to use pyspark.

**Comment by tobymao** [comment]
not really, because there's no way for you to ingest a spark dataframe into postgres in parallel, you have to convert it to a pandas dataframe anyways to move data from spark to postgres.

if you want your project to be distributed / spark, you should be using a spark gateway

**Comment by wahmedswl** [comment]
so, should i write to the main database within spark and just return None from the model?

**Comment by wahmedswl** [comment]
Isn't that possible at the sqlmesh level that if Pyspark DataFrame is returned then sqlmesh also use pyspark to push data to the main gateway/source?

Technically, we picked pyspark for scalability and we just want sqlmesh to insert data to the source/gateway efficiently.
