### ISSUE TITLE
Databricks Connect Serverless Config Bug

### ISSUE THREAD

**Issue by sungchun12** [TobikoData/sqlmesh#3325]
I'm trying to test out Databrick Connect with Serverless compute but it keeps erroring out. This is an in progress config.

```yaml
gateways:
    # use this for a realistic project
    # databricks cluster version: 14.3 LTS (includes Apache Spark 3.5.0, Scala 2.12)
    # python version: 3.10.13
    databricks_demo:
        connection:
            concurrent_tasks: 24
            type: databricks
            force_databricks_connect: true
            databricks_connect_use_serverless: True
            server_hostname: dbc-b9f590c4-0a08.cloud.databricks.com
            # http_path: /sql/protocolv1/o/5705746990502068/0603-211256-ns7ii2e2
            access_token: {{ env_var('DATABRICKS_ACCESS_TOKEN') }}
            catalog: public_demo
        state_connection: # this will be replaced with Tobiko Cloud
            type: postgres
            host: {{ env_var('SQLMESH_STATE_HOST') }}
            port: 5432
            user: {{ env_var('SQLMESH_STATE_USERNAME') }}
            password: {{ env_var('SQLMESH_STATE_PASSWORD') }}
            database: sqlmesh_state_databricks_demo
        test_connection:
            type: databricks
            force_databricks_connect: true
            databricks_connect_use_serverless: True
            server_hostname: dbc-b9f590c4-0a08.cloud.databricks.com
            # http_path: /sql/protocolv1/o/5705746990502068/0603-211256-ns7ii2e2
            access_token: {{ env_var('DATABRICKS_ACCESS_TOKEN') }}
```

```shell
(venv) ➜  sqlmesh-demos git:(databricks-demo) ✗ sqlmesh --debug info
2024-11-01 11:18:27,645 - MainThread - sqlmesh.cli.main - ERROR - Failed to initialize SQLMesh context (main.py:104)
Traceback (most recent call last):
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/cli/main.py", line 96, in cli
    context = Context(
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/core/context.py", line 365, in __init__
    self._engine_adapter = engine_adapter or self._connection_config.create_engine_adapter()
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/core/config/connection.py", line 120, in create_engine_adapter
    self._connection_factory_with_kwargs,
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/core/config/connection.py", line 108, in _connection_factory_with_kwargs
    **self._static_connection_kwargs,
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/core/config/connection.py", line 738, in _static_connection_kwargs
    builder = DatabricksSession.builder.remote(
TypeError: DatabricksSession.Builder.remote() got an unexpected keyword argument 'serverless'
Traceback (most recent call last):
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/bin/sqlmesh", line 8, in <module>
    sys.exit(cli())
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/cli/__init__.py", line 31, in wrapper
    return handler(sqlmesh_context, lambda: func(*args, **kwargs))
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/cli/__init__.py", line 40, in _default_exception_handler
    return func()
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/cli/__init__.py", line 31, in <lambda>
    return handler(sqlmesh_context, lambda: func(*args, **kwargs))
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/cli/main.py", line 96, in cli
    context = Context(
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/core/context.py", line 365, in __init__
    self._engine_adapter = engine_adapter or self._connection_config.create_engine_adapter()
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/core/config/connection.py", line 120, in create_engine_adapter
    self._connection_factory_with_kwargs,
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/core/config/connection.py", line 108, in _connection_factory_with_kwargs
    **self._static_connection_kwargs,
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/core/config/connection.py", line 738, in _static_connection_kwargs
    builder = DatabricksSession.builder.remote(
TypeError: DatabricksSession.Builder.remote() got an unexpected keyword argument 'serverless'
```

When I add in the serverless keyword argument to the remote session builder in the databricks-connect library, it looks to work on a naive glance. Is there a way to fix this in SQLMesh or do I have to file and issue with Databricks?
```python

class DatabricksSession:
    """
    The entry point for Databricks Connect.
    Create a new Pyspark session which connects to a remote Spark cluster and executes specified
    DataFrame APIs.

    Examples
    --------
    >>> spark = DatabricksSession.builder.getOrCreate()
    >>> df = spark.range(10)
    >>> print(df)
    """
    class Builder:
        """
        Builder to construct connection parameters.
        An instance of this class can be created using DatabricksSession.builder.
        """
        def __init__(self):
            self._conn_string: Optional[str] = None
            self._host: Optional[str] = None
            self._cluster_id: Optional[str] = None
            self._token: Optional[str] = None
            self._config: Optional[Config] = None
            self._headers: dict[str, str] = dict()
            self._user_agent: str = os.environ.get("SPARK_CONNECT_USER_AGENT", "")
            self._profile: Optional[str] = None
            self._validate_session_enabled: Optional[bool] = None

        def remote(
            self,
            conn_string: str = None,
            *,
            host: str = None,
            cluster_id: str = None,
            token: str = None,
            user_agent: str = "",
            headers: Optional[dict[str, str]] = None,
            serverless: bool = False,
        ) -> "DatabricksSession.Builder":
            """
            Specify connection and authentication parameters to connect to the remote Databricks
            cluster. Either the conn_string parameter should be specified, or a combination of the
            host, cluster_id and token parameters, but not both.

            Parameters
            ----------
            conn_string : str, optional
                The full spark connect connection string starting with "sc://".
                See https://github.com/apache/spark/blob/master/connector/connect/docs/client-connection-string.md # noqa: E501
            host : str, optional
                The Databricks workspace URL
            cluster_id: str, optional
                The cluster identifier where the Databricks connect queries should be executed.
            token: str, optional
                The Databricks personal access token used to authenticate into the cluster and on
                whose behalf the queries are executed.
            user_agent: str, optional
                A user agent string identifying the application using the Databricks Connect module.
                Databricks Connect sends a set of standard information, such as, OS, Python version
                and the version of Databricks Connect included as a user agent to the service.
                The value provided here will be included along with the rest of the information.
                It is recommended to provide this value in the format "<product-name>/<version>"
                as described in https://datatracker.ietf.org/doc/html/rfc7231#section-5.5.3, but is
                not required.
            headers: dict[str, str], optional
                Headers to use while initializing Spark Connect (Databricks Internal Use).

            Returns
            -------
            DatabricksSession.Builder
                The same instance of this class with the values configured.

            Examples
            --------
            Using a simple conn_string
            >>> conn = "sc://foo-workspace.cloud.databricks.com/;token=dapi1234567890;x-databricks-cluster-id=0301-0300-abcdefab" # noqa: E501
            >>> spark = DatabricksSession.builder.remote(conn).getOrCreate()

            Using keyword parameters
            >>> conn = "sc://foo-workspace.cloud.databricks.com/;token=dapi1234567890;x-databricks-cluster-id=0301-0300-abcdefab" # noqa: E501
            >>> spark = DatabricksSession.builder.remote(
            >>>     host="foo-workspace.cloud.databricks.com",
            >>>     token="dapi1234567890",
            >>>     cluster_id="0301-0300-abcdefab"
            >>> ).getOrCreate()
            """
            self._conn_string = conn_string
            self.host(host)
            self.clusterId(cluster_id)
            self.token(token)
            self.userAgent(user_agent)
            self.headers(headers)
            return self
```

I get a net new error now. 
```shell
(venv) ➜  sqlmesh-demos git:(databricks-demo) ✗ sqlmesh --debug info
2024-11-01 11:19:26,886 - MainThread - sqlmesh.cli.main - ERROR - Failed to initialize SQLMesh context (main.py:104)
Traceback (most recent call last):
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/databricks/sdk/config.py", line 122, in __init__
    self._validate()
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/databricks/sdk/config.py", line 469, in _validate
    raise ValueError(f'validate: more than one authorization method configured: {names}')
ValueError: validate: more than one authorization method configured: google and pat

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/cli/main.py", line 96, in cli
    context = Context(
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/core/context.py", line 365, in __init__
    self._engine_adapter = engine_adapter or self._connection_config.create_engine_adapter()
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/core/config/connection.py", line 120, in create_engine_adapter
    self._connection_factory_with_kwargs,
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/core/config/connection.py", line 108, in _connection_factory_with_kwargs
    **self._static_connection_kwargs,
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/sqlmesh/core/config/connection.py", line 753, in _static_connection_kwargs
    spark=builder.userAgent("sqlmesh").getOrCreate(),
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/databricks/connect/session.py", line 361, in getOrCreate
    config = Config(
  File "/Users/sung/Desktop/git_repos/sqlmesh-demos/venv/lib/python3.10/site-packages/databricks/sdk/config.py", line 127, in __init__
    raise ValueError(message) from e
ValueError: validate: more than one authorization method configured: google and pat. Config: host=https://dbc-b9f590c4-0a08.cloud.databricks.com, token=***, google_credentials=***. Env: GOOGLE_CREDENTIALS
Error: validate: more than one authorization method configured: google and pat. Config: host=https://dbc-b9f590c4-0a08.cloud.databricks.com, token=***, google_credentials=***. Env: GOOGLE_CREDENTIALS
```

**Comment by eakmanrq** [comment]
Databricks-connect on Serverless is supported on 15.1+. 
<img width="843" alt="Screenshot 2024-11-01 at 12 34 33 PM" src="https://github.com/user-attachments/assets/2320733f-3148-44d0-8e47-1355f574b9c3">

https://docs.databricks.com/en/dev-tools/databricks-connect/python/install.html#requirements
