### ISSUE TITLE
SQLMesh UI fails with multi project setup (at least dbt + sqlmesh project)

### ISSUE THREAD

**Issue by Kayrnt** [TobikoData/sqlmesh#3335]
## Description
Running a command such as:
`sqlmesh -p ./dbt_project -p ./sqlmesh_project ui` would fail with following stacktrace

```
22:26:21  Registered adapter: bigquery=1.8.3
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/sqlmesh/bin/sqlmesh", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/anaconda3/envs/sqlmesh/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/sqlmesh/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/sqlmesh/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/sqlmesh/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/sqlmesh/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/sqlmesh/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/cli/__init__.py", line 31, in wrapper
    return handler(sqlmesh_context, lambda: func(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/cli/__init__.py", line 40, in _default_exception_handler
    return func()
           ^^^^^^
  File "/opt/homebrew/anaconda3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/cli/__init__.py", line 31, in <lambda>
    return handler(sqlmesh_context, lambda: func(*args, **kwargs))
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/core/analytics/__init__.py", line 71, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/sqlmesh/lib/python3.11/site-packages/sqlmesh/cli/main.py", line 712, in ui
    os.environ["PROJECT_PATH"] = ctx.obj
    ~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "<frozen os>", line 684, in __setitem__
  File "<frozen os>", line 758, in encode
TypeError: str expected, not Context
make: *** [ui] Error 1
```

SQLMesh version used: 0.130.2

## To reproduce it
You may clone https://github.com/bqbooster/dbt_sqlmesh_multi_project and run the command `sqlmesh -p ./dbt_project -p ./sqlmesh_project ui` (or use `make ui`)

**Comment by Koosha-Metricforge** [comment]
Any update on how to fix this? Or is there any workaround suggested?

**Comment by tobymao** [comment]
the current ui doesn't support multi repo, it's going to be deprecated soon in favor of vs-code so there are no plans to address this

**Comment by Koosha-Metricforge** [comment]
Oh perfect, the vs-code extension you mean? That would be an excellent workaround for us. Many thanks Toby! Appreciate the new tools!
