### ISSUE TITLE
Non passing tests for model with arrays and order by throw an exception

### ISSUE THREAD

**Issue by esciara** [TobikoData/sqlmesh#3352]
```shell
sqlmesh --version
0.131.0
```

When the test of the following model does not pass, an exception is thrown. When the `ORDER BY` part of the sql is removed, the exception is not thrown.

Model:
```sql
MODEL (
  name sandbox.order_by_and_arrays_bug,
  kind FULL
);

SELECT
    ARRAY_AGG(DISTINCT id_contact_b ORDER BY id_contact_b) AS aggregated_duplicates
FROM
    sandbox.x420_source
GROUP BY
    id_contact_a
ORDER BY
    id_contact_a
```

Passing test:
```yaml
test_arrays_bug:
  model: sandbox.order_by_and_arrays_bug
  inputs:
    sandbox.x420_source:
    - id_contact_a: a
      id_contact_b: b
    - id_contact_a: a
      id_contact_b: c
  outputs:
    query:
    - aggregated_duplicates:
      - b
      - c
```

Non passing test (b and c are in reverse order):
```yaml
test_arrays_bug:
  model: sandbox.order_by_and_arrays_bug
  inputs:
    sandbox.x420_source:
    - id_contact_a: a
      id_contact_b: b
    - id_contact_a: a
      id_contact_b: c
  outputs:
    query:
    - aggregated_duplicates:
      - c
      - b
```

Exception thrown when running test:
```shell
sqlmesh test
...E......
======================================================================
ERROR: test_arrays_bug (/project-dir/tests/test_arrays_bug.yaml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/project-dir/.venv/lib/python3.12/site-packages/sqlmesh/core/test/definition.py", line 246, in assert_equal
    pd.testing.assert_frame_equal(
  File "/project-dir/.venv/lib/python3.12/site-packages/pandas/_testing/asserters.py", line 1279, in assert_frame_equal
    assert_series_equal(
  File "/project-dir/.venv/lib/python3.12/site-packages/pandas/_testing/asserters.py", line 1067, in assert_series_equal
    _testing.assert_almost_equal(
  File "testing.pyx", line 55, in pandas._libs.testing.assert_almost_equal
  File "testing.pyx", line 173, in pandas._libs.testing.assert_almost_equal
  File "/project-dir/.venv/lib/python3.12/site-packages/pandas/_testing/asserters.py", line 614, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.iloc[:, 0] (column name="aggregated_duplicates") are different

DataFrame.iloc[:, 0] (column name="aggregated_duplicates") values are different (100.0 %)
[index]: [0]
[left]:  [[c, b]]
[right]: [[b, c]]
At positional index 0, first diff: ['c', 'b'] != ['b' 'c']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project-dir/.venv/lib/python3.12/site-packages/sqlmesh/core/test/definition.py", line 567, in runTest
    self.assert_equal(expected, actual, sort=sort, partial=partial)
  File "/project-dir/.venv/lib/python3.12/site-packages/sqlmesh/core/test/definition.py", line 269, in assert_equal
    diff = expected.compare(actual).rename(columns={"self": "exp", "other": "act"})
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project-dir/.venv/lib/python3.12/site-packages/pandas/core/frame.py", line 8593, in compare
    return super().compare(
           ^^^^^^^^^^^^^^^^
  File "/project-dir/.venv/lib/python3.12/site-packages/pandas/core/generic.py", line 10121, in compare
    mask = ~((self == other) | (self.isna() & other.isna()))
              ^^^^^^^^^^^^^
  File "/project-dir/.venv/lib/python3.12/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/project-dir/.venv/lib/python3.12/site-packages/pandas/core/arraylike.py", line 40, in __eq__
    return self._cmp_method(other, operator.eq)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project-dir/.venv/lib/python3.12/site-packages/pandas/core/frame.py", line 7900, in _cmp_method
    new_data = self._dispatch_frame_op(other, op, axis=axis)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project-dir/.venv/lib/python3.12/site-packages/pandas/core/frame.py", line 7956, in _dispatch_frame_op
    bm = self._mgr.operate_blockwise(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project-dir/.venv/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 1511, in operate_blockwise
    return operate_blockwise(self, other, array_op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project-dir/.venv/lib/python3.12/site-packages/pandas/core/internals/ops.py", line 65, in operate_blockwise
    res_values = array_op(lvals, rvals)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/project-dir/.venv/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 344, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project-dir/.venv/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 127, in comp_method_OBJECT_ARRAY
    result = libops.vec_compare(x.ravel(), y.ravel(), op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ops.pyx", line 173, in pandas._libs.ops.vec_compare
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

----------------------------------------------------------------------
Ran 10 tests in 0.162s

FAILED (errors=1)
```

Model without `ORDER BY`:
```sql
MODEL (
  name sandbox.order_by_and_arrays_bug,
  kind FULL
);

SELECT
    ARRAY_AGG(DISTINCT id_contact_b ORDER BY id_contact_b) AS aggregated_duplicates
FROM
    sandbox.x420_source
GROUP BY
    id_contact_a
```

Resulting non passing test:
```shell
sqlmesh test
...F......
======================================================================
FAIL: test_arrays_bug (/project-dir/tests/test_arrays_bug.yaml)
----------------------------------------------------------------------
AssertionError: Data mismatch (exp: expected, act: actual)

  aggregated_duplicates        
                    exp     act
0                (c, b)  (b, c)

----------------------------------------------------------------------
Ran 10 tests in 0.159s

FAILED (failures=1)
```

**Comment by georgesittas** [comment]
Hey @esciara, can you elaborate on what's the issue here? Isn't this behavior reasonable, given that you're ordering by `id_contact_b` within the `ARRAY_AGG` call?

**Comment by esciara** [comment]
@georgesittas the fact the test is not passing is completely reasonable. The fact it throws an exception, thus the test showing as an error, is not.

I would expect a failure, not an error. In fact, I should have the exact message that is shown when not using `ORDER BY`.
