### ISSUE TITLE
Missing table when using Astronomer as scheduler

### ISSUE THREAD

**Issue by julesmga** [TobikoData/sqlmesh#3362]
When trying to deploy sqlmesh on an astronomer instance, the sqlmesh dag fails to load with the following error:

```
[2024-11-12T15:51:40.391+0000] {dagbag.py:387} ERROR - Failed to import: /usr/local/airflow/dags/sqlmesh.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/local/airflow/dags/sqlmesh.py", line 7, in <module>
    for dag in sqlmesh_airflow.dags:
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlmesh/schedulers/airflow/integration.py", line 140, in dags
    prod_env = state_sync.get_environment(c.PROD)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlmesh/core/state_sync/base.py", line 449, in delegate
    return getattr(self.state_sync, name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlmesh/core/state_sync/engine_adapter.py", line 677, in get_environment
    return self._get_environment(environment)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlmesh/core/state_sync/engine_adapter.py", line 899, in _get_environment
    row = self._fetchone(
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlmesh/core/state_sync/engine_adapter.py", line 180, in _fetchone
    return self.engine_adapter.fetchone(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlmesh/core/engine_adapter/base.py", line 1899, in fetchone
    self.execute(
  File "/usr/local/lib/python3.12/site-packages/sqlmesh/core/engine_adapter/base.py", line 2059, in execute
    self._execute(sql, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/sqlmesh/core/engine_adapter/base.py", line 2065, in _execute
    self.cursor.execute(sql, **kwargs)
psycopg2.errors.UndefinedTable: relation "sqlmesh._environments" does not exist
LINE 1: ...rt_at", "snapshots", "catalog_name_override" FROM "sqlmesh"....
                                                             ^

/usr/local/lib/python3.12/site-packages/snowflake/sqlalchemy/base.py:1068 SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
```

Running the generated docker image locally works fine though, could that be a permission issue on the underlying database when running on Astronomer?

Do note that we are using the free Astronomer trial to evaluate it before committing to it.

**Comment by julesmga** [comment]
Thank you, works like a charm with an external db.
