### ISSUE TITLE
SQLMesh migration fails on Dataricks

### ISSUE THREAD

**Issue by zerodarkzone** [TobikoData/sqlmesh#3407]
Hi,

I'm using SQLMesh v0.110.0 on databricks and I'm trying to upgrade to v0.133.0. I'm running the commad `sqlmesh migrate` but it fails with the following error:

``` python
2024-11-21 12:28:24,432 - MainThread - sqlmesh.cli - ERROR - Unhandled exception (__init__.py:57)
Traceback (most recent call last):
  File "/home/juanb/mambaforge-pypy3/envs/priceshoes/lib/python3.10/site-packages/sqlmesh/core/state_sync/engine_adapter.py", line 1224, in migrate
    migrate_rows = self._apply_migrations(default_catalog, skip_backup)
  File "/home/juanb/mambaforge-pypy3/envs/priceshoes/lib/python3.10/site-packages/sqlmesh/core/state_sync/engine_adapter.py", line 1315, in _apply_migrations
    migration.migrate(self, default_catalog=default_catalog)
  File "/home/juanb/mambaforge-pypy3/envs/priceshoes/lib/python3.10/site-packages/sqlmesh/migrations/v0055_add_updated_ts_unpaused_ts_ttl_ms_unrestorable_to_snapshot.py", line 52, in migrate
    engine_adapter.execute(drop_column_exp)
  File "/home/juanb/mambaforge-pypy3/envs/priceshoes/lib/python3.10/site-packages/sqlmesh/core/engine_adapter/base.py", line 2059, in execute
    self._execute(sql, **kwargs)
  File "/home/juanb/mambaforge-pypy3/envs/priceshoes/lib/python3.10/site-packages/sqlmesh/core/engine_adapter/base.py", line 2065, in _execute
    self.cursor.execute(sql, **kwargs)
  File "/home/juanb/mambaforge-pypy3/envs/priceshoes/lib/python3.10/site-packages/databricks/sql/client.py", line 768, in execute
    execute_response = self.thrift_backend.execute_command(
  File "/home/juanb/mambaforge-pypy3/envs/priceshoes/lib/python3.10/site-packages/databricks/sql/thrift_backend.py", line 869, in execute_command
    return self._handle_execute_response(resp, cursor)
  File "/home/juanb/mambaforge-pypy3/envs/priceshoes/lib/python3.10/site-packages/databricks/sql/thrift_backend.py", line 961, in _handle_execute_response
    final_operation_state = self._wait_until_command_done(
  File "/home/juanb/mambaforge-pypy3/envs/priceshoes/lib/python3.10/site-packages/databricks/sql/thrift_backend.py", line 794, in _wait_until_command_done
    self._check_command_not_in_error_or_closed_state(
  File "/home/juanb/mambaforge-pypy3/envs/priceshoes/lib/python3.10/site-packages/databricks/sql/thrift_backend.py", line 598, in _check_command_not_in_error_or_closed_state       
    raise ServerOperationError(
databricks.sql.exc.ServerOperationError: [DELTA_UNSUPPORTED_DROP_COLUMN] DROP COLUMN is not supported for your Delta table.
Please enable Column Mapping on your Delta table with mapping mode 'name'.
You can use one of the following commands.

If your table is already on the required protocol version:
ALTER TABLE table_name SET TBLPROPERTIES ('delta.columnMapping.mode' = 'name')

If your table is not on the required protocol version and requires a protocol upgrade:
ALTER TABLE table_name SET TBLPROPERTIES (
   'delta.columnMapping.mode' = 'name',
   'delta.minReaderVersion' = '2',
   'delta.minWriterVersion' = '5')
Refer to table versioning at https://docs.databricks.com/delta/versioning.html

```

It has to do with the ability to DROP and RENAME columns in databricks. I know is possible to activate this feature in the models but there's no way to do it on the tables that sqlmesh uses to track the status.

**Comment by tobymao** [comment]
you should be able to do a manual ddl on the databricks table tracking state, it should be something like sqlmesh._snapshots. this will allow you to do drop/rename columns

in general, we don't recommend using databricks for state, you can contact us for our cloud offering which has managed state or set up postgres.

**Comment by zerodarkzone** [comment]
Sqlmesh recreates the tables when doing the migrations so it is not possible to do it

**Comment by tobymao** [comment]
in that case, i’d suggest you try to set a default value or switch the postgres
