### ISSUE TITLE
Using pydantic @validator in python model

### ISSUE THREAD

**Issue by SilasFriby** [TobikoData/sqlmesh#3537]
Hi there,

In my python model I am extracting data from an external API. In the process of extracting data I use a pydantic model to validate the query parameters used in the API request. This works fine as long as I do not use @validaor in my pydantic model. However, if my pydantc model uses a @validator I get an error message when executing ```sqlmesh plan``` command. I have added a very simple example to illustrate the problem and the corresponding error message.

```python
# models/my_python_model.py

from utils.data_models import QueryParamsDataModel
from utils.fetch_data import fetch_data

@model(some parameters...)
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    **kwargs
) -> pd.DataFrame:

    # Set query params
    param1 = 1
    
    # Validate query params
    QueryParamsModel(param1=param1)

    # Fetch API data
    df = fetch_data(...)
    
    return df
```

where QueryParamsDataModel is defined by

```python
class QueryParamsDataModel(BaseModel):
    param1: int

   @validator('value')
    def validate_value(cls, v):
        if v < 0:
            raise ValueError("Value must be non-negative")
        return v
```

The when running ```sqlmesh plan``` we get error

```bash
Traceback (most recent call last):
  File "/workspaces/solid_data/.venv/bin/sqlmesh", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/sqlmesh/cli/__init__.py", line 31, in wrapper
    return handler(sqlmesh_context, lambda: func(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/sqlmesh/cli/__init__.py", line 40, in _default_exception_handler
    return func()
           ^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/sqlmesh/cli/__init__.py", line 31, in <lambda>
    return handler(sqlmesh_context, lambda: func(*args, **kwargs))
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/sqlmesh/cli/main.py", line 96, in cli
    context = Context(
              ^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/sqlmesh/core/context.py", line 406, in __init__
    self.load()
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/sqlmesh/core/context.py", line 559, in load
    projects.append(context_loader.loader.load(self, update_schemas))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/sqlmesh/core/loader.py", line 106, in load
    models = self._load_models(macros, jinja_macros, context.selected_gateway, audits)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/sqlmesh/core/loader.py", line 330, in _load_models
    models.update(self._load_python_models(macros, jinja_macros, audits))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/sqlmesh/core/loader.py", line 422, in _load_python_models
    model = registry[name].model(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/sqlmesh/core/model/decorator.py", line 149, in model
    return create_python_model(self.name, entrypoint, **common_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/sqlmesh/core/model/definition.py", line 1858, in create_python_model
    parse_dependencies(python_env, entrypoint) if python_env is not None else (set(), set())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/sqlmesh/core/model/common.py", line 113, in parse_dependencies
    env = prepare_env(python_env)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/sqlmesh/utils/metaprogramming.py", line 425, in prepare_env
    exec(executable.payload, env)
  File "<string>", line 1, in <module>
  File "<string>", line 4, in QueryParamsDataModel
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/pydantic/class_validators.py", line 93, in dec
    f_cls = _prepare_validator(f, allow_reuse)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/solid_data/.venv/lib/python3.12/site-packages/pydantic/class_validators.py", line 151, in _prepare_validator
    getattr(f_cls.__func__, '__module__', '<No __module__>')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

However, if we instead use the hack below, i.e replace @validator with __post_init__ everything works fine.

```python
class QueryParamsDataModel(BaseModel):
    param1: int

    def __post_init__(self):
        if self.value < 0:
            raise ValueError("Value must be non-negative")
 ```
 
 It is possible to solve this, so that I can use @validator (or perhaps even better @field_validator from pydantic v2) or do I need to use the hack with __post_init__?
 
 Best regards
 Silas

**Comment by georgesittas** [comment]
Hi @SilasFriby,

I wasn't able to reproduce this issue locally against the latest main branch. I used this as an example, and it ran fine:

```python
import pandas as pd
from pydantic import BaseModel, field_validator, validator

from sqlmesh import model


class DataModel(BaseModel):
    value: int

    # @field_validator("value")
    @validator("value")
    def validate_value(cls, v):
        if v < 0:
            raise ValueError("Value must be non-negative")
        return v


@model("test_model", kind="FULL", columns={"value": "int"})
def execute(context, start, end, **kwargs):
    value = 1
    validated_value = DataModel(value=value)
    return pd.DataFrame({"value": [validated_value.value]})
```

Do you see any noteworthy differences compared to what you have?

**Comment by tobymao** [comment]
probably because they are using pydantic v1 syntax

**Comment by SilasFriby** [comment]
> Hi @SilasFriby,
> 
> I wasn't able to reproduce this issue locally against the latest main branch. I used this as an example, and it ran fine:
> 
> ```python
> import pandas as pd
> from pydantic import BaseModel, field_validator, validator
> 
> from sqlmesh import model
> 
> 
> class DataModel(BaseModel):
>     value: int
> 
>     # @field_validator("value")
>     @validator("value")
>     def validate_value(cls, v):
>         if v < 0:
>             raise ValueError("Value must be non-negative")
>         return v
> 
> 
> @model("test_model", kind="FULL", columns={"value": "int"})
> def execute(context, start, end, **kwargs):
>     value = 1
>     validated_value = DataModel(value=value)
>     return pd.DataFrame({"value": [validated_value.value]})
> ```
> 
> Do you see any noteworthy differences compared to what you have?

Your code example also produces same error on my local machine... weird..

**Comment by SilasFriby** [comment]
@georgesittas, your code example also produces the error ```TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'```onmy machine.

@tobymao, 'value' was a typo, it should of course have been 'param1' in the validator..

**Comment by georgesittas** [comment]
What version of pydantic are you using?

**Comment by SilasFriby** [comment]
I got errors when using pydantic 2.10.4 (using field_validator), so therefore I switched to pydantic 1.10.19 (and changed to validator).

However, I just started a fresh project using suing your example code by initialing with ```sqlmesh init duckdb```. And then the model

```python
import pandas as pd
from pydantic import BaseModel, field_validator, validator

from sqlmesh import model

class DataModel(BaseModel):
    value: int

    # @field_validator("value")
    @validator("value")
    def validate_value(cls, v):
        if v < 0:
            raise ValueError("Value must be non-negative")
        return v


@model("test_model", kind="FULL", columns={"value": "int"})
def execute(context, start, end, **kwargs):
    value = 1
    validated_value = DataModel(value=value)
    return pd.DataFrame({"value": [validated_value.value]})
```

works fine.

However, in my other project I am 1) using sqlmesh[mssql] and 2) developing in a dev container, because I cannot get pymssql to work on my M3.

So the root cause of my issue my be found there..

Anyway, I will do some more troubleshooting, starting with attempting to use pydantic 2.10.4 again

**Comment by SilasFriby** [comment]
Your example works in my dev container now. So all is good for now. 

A small (and perhaps irrelevant) note: In the SQLMesh docs it says that Pydantic v1 is the default, however this is no longer the case.

Anyway, thanks for you quick replies.

**Comment by georgesittas** [comment]
Thanks for the heads up, we're going to amend soon.
