### ISSUE TITLE
pyarrow type error when working with sqlmesh apply

### ISSUE THREAD

**Issue by hughcameron** [TobikoData/sqlmesh#869]
I'm encountering an error when trying to run sqlmesh on a BigQuery dataset. I'm using the following command:

`SQLMESH_DEBUG=1 sqlmesh plan prod`

The final console output I'm getting is below. I've troubleshooted this by installing different versions of python (9, 10 & 11) and pyarrow (11 & 12), but I'm still getting the same error. I've truncated some table names with `...` for privacy reasons.

The expected behaviour is that the plan should be generated and the environment should be promoted.

```
All model batches have been executed successfully

2023-05-18 15:06:40,763 - sqlmesh.core.state_sync.common - INFO - Promoting environment 'prod' (common.py:89)
2023-05-18 15:06:40,767 - sqlmesh.core.engine_adapter.bigquery - DEBUG - Executing SQL:
SELECT snapshot FROM sqlmesh._snapshots WHERE (name, identifier) IN (('blueprint.raw_audits', '3698478436') ... ) (bigquery.py:402)
2023-05-18 15:06:41,416 - urllib3.connectionpool - DEBUG - https://bigquery.googleapis.com:443 "POST /bigquery/v2/projects/business-intelligence-zitcha/jobs?prettyPrint=false HTTP/1.1" 200 None (connectionpool.py:456)
2023-05-18 15:06:41,813 - urllib3.connectionpool - DEBUG - https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/business-intelligence-zitcha/queries/b92c9906-7953-40c0-afb6-87e5f4ab4d89?maxResults=0&location=US&prettyPrint=false HTTP/1.1" 200 None (connectionpool.py:456)
2023-05-18 15:06:42,234 - urllib3.connectionpool - DEBUG - https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/business-intelligence-zitcha/queries/b92c9906-7953-40c0-afb6-87e5f4ab4d89?fields=jobReference%2CtotalRows%2CpageToken%2Crows&location=US&formatOptions.useInt64Timestamp=True&prettyPrint=false HTTP/1.1" 200 None (connectionpool.py:456)
2023-05-18 15:06:42,501 - sqlmesh.core.engine_adapter.bigquery - DEBUG - Executing SQL:
SELECT name, snapshots, start_at, end_at, plan_id, previous_plan_id, expiration_ts, finalized_ts FROM sqlmesh._environments WHERE name = 'prod' (bigquery.py:402)
2023-05-18 15:06:43,062 - urllib3.connectionpool - DEBUG - https://bigquery.googleapis.com:443 "POST /bigquery/v2/projects/business-intelligence-zitcha/jobs?prettyPrint=false HTTP/1.1" 200 None (connectionpool.py:456)
2023-05-18 15:06:43,442 - urllib3.connectionpool - DEBUG - https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/business-intelligence-zitcha/queries/de3221dd-3c60-4499-b321-7c9d7e7b712e?maxResults=0&location=US&prettyPrint=false HTTP/1.1" 200 None (connectionpool.py:456)
2023-05-18 15:06:43,455 - sqlmesh.core.engine_adapter.bigquery - DEBUG - Executing SQL:
DELETE FROM sqlmesh._environments WHERE name = 'prod' (bigquery.py:402)
2023-05-18 15:06:44,000 - urllib3.connectionpool - DEBUG - https://bigquery.googleapis.com:443 "POST /bigquery/v2/projects/business-intelligence-zitcha/jobs?prettyPrint=false HTTP/1.1" 200 None (connectionpool.py:456)
2023-05-18 15:06:45,488 - urllib3.connectionpool - DEBUG - https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/business-intelligence-zitcha/queries/13ce790d-e460-4c56-a626-a0b4fc2a2ff3?maxResults=0&location=US&prettyPrint=false HTTP/1.1" 200 None (connectionpool.py:456)
2023-05-18 15:06:45,771 - urllib3.connectionpool - DEBUG - https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/business-intelligence-zitcha/jobs/13ce790d-e460-4c56-a626-a0b4fc2a2ff3?location=US&prettyPrint=false HTTP/1.1" 200 None (connectionpool.py:456)
2023-05-18 15:06:46,133 - urllib3.connectionpool - DEBUG - https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/business-intelligence-zitcha/datasets/sqlmesh/tables/_environments?prettyPrint=false HTTP/1.1" 200 None (connectionpool.py:456)
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/bin/sqlmesh", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/sqlmesh/cli/main.py", line 236, in plan
    context.plan(environment, restate_models=restate_models, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/sqlmesh/core/context.py", line 646, in plan
    self.console.plan(plan, auto_apply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/sqlmesh/core/console.py", line 289, in plan
    self._show_options_after_categorization(plan, auto_apply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/sqlmesh/core/console.py", line 300, in _show_options_after_categorization
    self._prompt_backfill(plan, auto_apply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/sqlmesh/core/console.py", line 398, in _prompt_backfill
    plan.apply()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/sqlmesh/core/plan/definition.py", line 300, in apply
    self._apply(self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/sqlmesh/core/context.py", line 665, in apply
    self._scheduler.create_plan_evaluator(self).evaluate(plan)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/sqlmesh/core/plan/evaluator.py", line 69, in evaluate
    task(plan)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/sqlmesh/core/plan/evaluator.py", line 124, in _promote
    added, removed = self.state_sync.promote(environment, no_gaps=plan.no_gaps)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/sqlmesh/core/state_sync/common.py", line 36, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/sqlmesh/core/state_sync/common.py", line 129, in promote
    self._update_environment(environment)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/sqlmesh/core/state_sync/engine_adapter.py", line 235, in _update_environment
    self.engine_adapter.insert_append(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/sqlmesh/core/engine_adapter/base.py", line 460, in insert_append
    self._insert_append_pandas_df(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/sqlmesh/core/engine_adapter/bigquery.py", line 165, in _insert_append_pandas_df
    self.__load_pandas_to_table(table, df, replace=False)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/sqlmesh/core/engine_adapter/bigquery.py", line 182, in __load_pandas_to_table
    result = self.client.load_table_from_dataframe(df, table, job_config=job_config).result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 2697, in load_table_from_dataframe
    _pandas_helpers.dataframe_to_parquet(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 719, in dataframe_to_parquet
    arrow_table = dataframe_to_arrow(dataframe, bq_schema)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 662, in dataframe_to_arrow
    bq_to_arrow_array(get_column_or_index(dataframe, bq_field.name), bq_field)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 380, in bq_to_arrow_array
    return pyarrow.Array.from_pandas(series, type=arrow_type)
  File "pyarrow/array.pxi", line 1044, in pyarrow.lib.Array.from_pandas
  File "pyarrow/array.pxi", line 316, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 123, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: Expected a string or bytes dtype, got int64
```

**Comment by tobymao** [comment]
this is fixed
