### ISSUE TITLE
sqlmesh prompt command failing

### ISSUE THREAD

**Issue by SumanthPuram** [TobikoData/sqlmesh#899]
I discovered the prompt command today. I tried to use but it failed. Help command wasn't sufficient. Anything else I need to do?

```
❯ sqlmesh prompt "get me top n  employees"
Traceback (most recent call last):
  File "/Users/sumanth/Library/Python/3.10/bin//sqlmesh", line 8, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sumanth/Library/Python/3.10/lib/python/site-packages/sqlmesh/cli/__init__.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "/Users/sumanth/Library/Python/3.10/lib/python/site-packages/sqlmesh/cli/main.py", line 417, in prompt
    from sqlmesh.integrations.llm import LLMIntegration
  File "/Users/sumanth/Library/Python/3.10/lib/python/site-packages/sqlmesh/integrations/llm.py", line 5, in <module>
    from langchain import LLMChain, PromptTemplate
ModuleNotFoundError: No module named 'langchain'
```

**Comment by GeorgeSittas** [comment]
There are some dependencies missing I guess, can you try running the following?

```python
pip install -e ".[llm]"
```

**Comment by SumanthPuram** [comment]
It worked. Thanks! 

Let me know if should close this right away or you want to add some dependencies and close this.

**Comment by GeorgeSittas** [comment]
Cool!

I think we want to keep this as optional instead of installing the dependencies by default, since it's an experimental feature and not really needed for the core product.

I'm gonna go ahead and close the issue, cc @izeigerman
