### ISSUE TITLE
Error when creating external models

### ISSUE THREAD

**Issue by hughcameron** [TobikoData/sqlmesh#919]
I'm encountering an error when trying to create external models.

Based on my reading of the documentation, `sqlmesh create_external_models` accepts no arguments and should be run from the root of the project.

The expected behaviour is for the CLI to create an external model represented as a YAML file as [described here](https://sqlmesh.readthedocs.io/en/stable/concepts/models/external_models/#using-the-create_external_models-cli-command).

Please see below the stack trace.

```bash
sqlmesh create_external_models
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/bin/sqlmesh", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlmesh/cli/__init__.py", line 20, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlmesh/cli/main.py", line 392, in create_external_models
    obj.create_external_models()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlmesh/core/context.py", line 847, in create_external_models
    models = self._models or self._loader.load(self, update_schemas=False).models
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlmesh/core/loader.py", line 132, in load
    macros, hooks, jinja_macros = self._load_scripts()
                                  ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlmesh/core/loader.py", line 226, in _load_scripts
    if self._import_python_file(path, context_path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlmesh/core/loader.py", line 366, in _import_python_file
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'macros'
```

Also, here's a list of versions I'm running:

```bash
❯ pip list | grep sql
sqlglot                       14.1.1
sqlmesh                       0.12.2
sqlparse                      0.4.4
```

**Comment by tobymao** [comment]
this is already fixed. 

https://github.com/TobikoData/sqlmesh/pull/914

we can deploy a new version after the weekend

**Comment by tobymao** [comment]
the current main was pretty minimal, so i decided to deploy v0.12.3

**Comment by hughcameron** [comment]
Thanks @tobymao - I just updated and I'm seeing this response:

```bash
SQLMESH_DEBUG=1 sql create_external_models
2023-05-29 12:21:52,920 - tzlocal - DEBUG - /etc/localtime found (unix.py:122)
2023-05-29 12:21:52,921 - tzlocal - DEBUG - 1 found:
 {'/etc/localtime is a symlink to': 'Australia/Brisbane'} (unix.py:138)
2023-05-29 12:21:53,337 - shapely.geos - DEBUG - Formed path for globbing: dylib_path='/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/shapely/.dylibs/*.dylib' (geos.py:115)
2023-05-29 12:21:53,337 - shapely.geos - DEBUG - Globbed: geos_whl_dylib=[] (geos.py:118)
2023-05-29 12:21:53,581 - google.cloud.bigquery.opentelemetry_tracing - DEBUG - This service is instrumented using OpenTelemetry. OpenTelemetry or one of its components could not be imported; please add compatible versions of opentelemetry-api and opentelemetry-instrumentation packages in order to get BigQuery Tracing data. (opentelemetry_tracing.py:66)
2023-05-29 12:21:53,581 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None) (retry.py:282)
2023-05-29 12:21:53,583 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token (requests.py:192)
2023-05-29 12:21:53,591 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443 (connectionpool.py:1048)
2023-05-29 12:21:53,617 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None) (retry.py:282)
2023-05-29 12:21:53,618 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token (requests.py:192)
2023-05-29 12:21:53,619 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443 (connectionpool.py:1048)
2023-05-29 12:21:53,652 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None) (retry.py:282)
2023-05-29 12:21:53,653 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token (requests.py:192)
2023-05-29 12:21:53,660 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443 (connectionpool.py:1048)
2023-05-29 12:21:53,688 - urllib3.util.retry - DEBUG - Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None) (retry.py:282)
2023-05-29 12:21:53,689 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token (requests.py:192)
2023-05-29 12:21:53,693 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443 (connectionpool.py:1048)
2023-05-29 12:21:53,864 - urllib3.connectionpool - DEBUG - https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None (connectionpool.py:546)
2023-05-29 12:21:53,866 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): bigquery.googleapis.com:443 (connectionpool.py:1048)
2023-05-29 12:21:53,906 - urllib3.connectionpool - DEBUG - https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None (connectionpool.py:546)
2023-05-29 12:21:53,909 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): bigquery.googleapis.com:443 (connectionpool.py:1048)
2023-05-29 12:21:53,923 - urllib3.connectionpool - DEBUG - https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None (connectionpool.py:546)
2023-05-29 12:21:53,927 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): bigquery.googleapis.com:443 (connectionpool.py:1048)
2023-05-29 12:21:53,964 - urllib3.connectionpool - DEBUG - https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None (connectionpool.py:546)
2023-05-29 12:21:53,966 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): bigquery.googleapis.com:443 (connectionpool.py:1048)
2023-05-29 12:21:54,336 - urllib3.connectionpool - DEBUG - https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/.../.../.../tables/...?prettyPrint=false HTTP/1.1" 200 None (connectionpool.py:546)
2023-05-29 12:21:54,390 - urllib3.connectionpool - DEBUG - https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/.../.../.../tables/...?prettyPrint=false HTTP/1.1" 200 None (connectionpool.py:546)
2023-05-29 12:21:54,413 - urllib3.connectionpool - DEBUG - https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/.../.../.../tables/...?prettyPrint=false HTTP/1.1" 200 None (connectionpool.py:546)
2023-05-29 12:21:54,440 - urllib3.connectionpool - DEBUG - https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/.../.../.../tables/...?prettyPrint=false HTTP/1.1" 200 None (connectionpool.py:546)
2023-05-29 12:21:54,687 - urllib3.connectionpool - DEBUG - https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/.../.../.../tables/...?prettyPrint=false HTTP/1.1" 200 None (connectionpool.py:546)
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlglot/parser.py", line 852, in parse_into
    return self._parse(parser, raw_tokens, sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlglot/parser.py", line 889, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlglot/parser.py", line 932, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 6.
  RECORD

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/bin/sqlmesh", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlmesh/cli/main.py", line 392, in create_external_models
    obj.create_external_models()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlmesh/core/context.py", line 851, in create_external_models
    create_schema_file(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlmesh/core/schema_loader.py", line 40, in create_schema_file
    for table, columns in sorted(
                          ^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlmesh/core/schema_loader.py", line 41, in <lambda>
    pool.map(lambda table: (table, adapter.columns(table)), external_tables)
                                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/bigquery.py", line 103, in columns
    return {
           ^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/bigquery.py", line 104, in <dictcomp>
    field.name: exp.DataType.build(field.field_type, dialect=self.dialect)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlglot/expressions.py", line 3320, in build
    data_type_exp = parse_one(dtype, read=dialect, into=DataType)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlglot/__init__.py", line 156, in parse_one
    result = dialect.parse_into(into, sql, **opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlglot/dialects/dialect.py", line 179, in parse_into
    return self.parser(**opts).parse_into(expression_type, self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlglot/parser.py", line 856, in parse_into
    raise ParseError(
sqlglot.errors.ParseError: Failed to parse into <class 'sqlglot.expressions.DataType'>
```

**Comment by tobymao** [comment]
can you show me what type it is trying to parse?

**Comment by tobymao** [comment]
you can cherry pick this https://github.com/tobymao/sqlglot/commit/264e9d7d8bf25db60e3dec1f6a5bee528c5300d6 to get a better error message, and then i can fix the parser if necessary

**Comment by hughcameron** [comment]
Sure, I've made that change and here's the response I'm seeing:

```bash
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dag/lib/python3.11/site-packages/sqlglot/parser.py", line 856, in parse_into
    raise ParseError(
sqlglot.errors.ParseError: Failed to parse 'RECORD' into <class 'sqlglot.expressions.DataType'>
```

**Comment by tobymao** [comment]
what is a record? is it the same thing as a struct?

**Comment by tobymao** [comment]
https://github.com/tobymao/sqlglot/commit/2792eaa1c06be3f6ff53201a4111f6e4a145d572

looks like record is a legacy name for struct
