### ISSUE TITLE
Unexpected change to DATE_DIFF in example project

### ISSUE THREAD

**Issue by hughcameron** [TobikoData/sqlmesh#942]
While testing the example project setup by `sqlmesh init` I encountered an issue with the `DATE_DIFF` function.

I added this model to the project:

```sql
MODEL (
  name sqlmesh_example.duration,
  kind FULL,
  cron '@daily',
);

SELECT
  id AS id,
  item_id AS item_id,
  ds AS ds,
  DATEDIFF('day', ds, CURRENT_DATE) AS days_ago
FROM sqlmesh_example.seed_model
```

And the plan failed as below:

```bash
SQLMESH_DEBUG=1 sql plan --auto-apply 
2023-06-05 21:18:59,811 - tzlocal - DEBUG - /etc/localtime found (unix.py:122)
2023-06-05 21:18:59,813 - tzlocal - DEBUG - 1 found:
 {'/etc/localtime is a symlink to': 'Australia/Brisbane'} (unix.py:138)
2023-06-05 21:18:59,830 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
CREATE SCHEMA IF NOT EXISTS sqlmesh_example (base.py:781)
2023-06-05 21:18:59,911 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
CREATE OR REPLACE VIEW sqlmesh_example.incremental_model__fixture (id, item_id, ds) AS SELECT CAST(id AS INT) AS id, CAST(item_id AS INT) AS item_id, CAST(ds AS TEXT) AS ds FROM (VALUES (1, 1, '2020-01-01'), (2, 1, '2020-01-02'), (3, 2, '2020-01-03')) AS t(id, item_id, ds) (base.py:781)
2023-06-05 21:18:59,913 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
SELECT incremental_model.item_id AS item_id, COUNT(DISTINCT incremental_model.id) AS num_orders FROM sqlmesh_example.incremental_model__fixture AS incremental_model GROUP BY incremental_model.item_id (base.py:781)
2023-06-05 21:18:59,920 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
DROP VIEW IF EXISTS sqlmesh_example.incremental_model (base.py:781)
======================================================================
Successfully Ran 1 tests against duckdb
----------------------------------------------------------------------
2023-06-05 21:18:59,923 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
DESCRIBE sqlmesh._versions (base.py:781)
2023-06-05 21:18:59,948 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
SELECT * FROM sqlmesh._versions (base.py:781)
2023-06-05 21:18:59,949 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
DESCRIBE sqlmesh._versions (base.py:781)
2023-06-05 21:18:59,955 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
SELECT * FROM sqlmesh._versions (base.py:781)
2023-06-05 21:18:59,955 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
SELECT name, snapshots, start_at, end_at, plan_id, previous_plan_id, expiration_ts, finalized_ts FROM sqlmesh._environments WHERE name = 'prod' (base.py:781)
2023-06-05 21:18:59,976 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
SELECT snapshot FROM sqlmesh._snapshots WHERE (name, identifier) IN (('sqlmesh_example.duration', '4038886598'), ('sqlmesh_example.seed_model', '2266916806'), ('sqlmesh_example.full_model', '1252029766'), ('sqlmesh_example.incremental_model', '3511663723')) (base.py:781)
2023-06-05 21:18:59,977 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
SELECT name, snapshots, start_at, end_at, plan_id, previous_plan_id, expiration_ts, finalized_ts FROM sqlmesh._environments WHERE name = 'prod' (base.py:781)
2023-06-05 21:18:59,978 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
SELECT name, snapshots, start_at, end_at, plan_id, previous_plan_id, expiration_ts, finalized_ts FROM sqlmesh._environments WHERE name = 'prod' (base.py:781)
2023-06-05 21:18:59,978 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
SELECT snapshot FROM sqlmesh._snapshots WHERE (name, identifier) IN (('sqlmesh_example.duration', '4038886598'), ('sqlmesh_example.seed_model', '2266916806'), ('sqlmesh_example.full_model', '1252029766'), ('sqlmesh_example.incremental_model', '3511663723')) (base.py:781)
2023-06-05 21:18:59,979 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
SELECT snapshot, content FROM sqlmesh._snapshots LEFT OUTER JOIN sqlmesh._seeds USING (name, identifier) WHERE FALSE (base.py:781)
New environment `prod` will be created from `prod`
Summary of differences against `prod`:
└── Added Models:
    ├── sqlmesh_example.seed_model
    ├── sqlmesh_example.duration
    ├── sqlmesh_example.full_model
    └── sqlmesh_example.incremental_model
2023-06-05 21:18:59,989 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
SELECT id, name, identifier, version, start_ts, end_ts, is_dev, is_removed FROM sqlmesh._intervals WHERE (name, version) IN (('sqlmesh_example.duration', '1374773906'), ('sqlmesh_example.seed_model', '3609019599'), ('sqlmesh_example.full_model', '272284751'), ('sqlmesh_example.incremental_model', '1626196238')) ORDER BY name NULLS FIRST, identifier NULLS FIRST, created_ts NULLS FIRST, is_removed NULLS FIRST (base.py:781)
Models needing backfill (missing dates):
├── sqlmesh_example.duration: 2023-06-04 - 2023-06-04
├── sqlmesh_example.seed_model: 2023-06-04 - 2023-06-04
├── sqlmesh_example.full_model: 2020-01-01 - 2023-06-04
└── sqlmesh_example.incremental_model: 2020-01-01 - 2023-06-04
2023-06-05 21:19:00,079 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
SELECT snapshot FROM sqlmesh._snapshots WHERE (name, identifier) IN (('sqlmesh_example.seed_model', '2266916806'), ('sqlmesh_example.incremental_model', '3511663723')) (base.py:781)
2023-06-05 21:19:00,080 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
CREATE SCHEMA IF NOT EXISTS sqlmesh__sqlmesh_example (base.py:781)
2023-06-05 21:19:00,080 - sqlmesh.core.snapshot.evaluator - INFO - Creating table 'sqlmesh__sqlmesh_example.sqlmesh_example__seed_model__3609019599' (evaluator.py:410)
2023-06-05 21:19:00,080 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
CREATE TABLE IF NOT EXISTS sqlmesh__sqlmesh_example.sqlmesh_example__seed_model__3609019599 (id INT, item_id INT, ds TEXT) (base.py:781)
2023-06-05 21:19:00,080 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
CREATE SCHEMA IF NOT EXISTS sqlmesh__sqlmesh_example (base.py:781)
2023-06-05 21:19:00,081 - sqlmesh.core.snapshot.evaluator - INFO - Creating table 'sqlmesh__sqlmesh_example.sqlmesh_example__incremental_model__1626196238' (evaluator.py:410)
2023-06-05 21:19:00,082 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
CREATE TABLE IF NOT EXISTS sqlmesh__sqlmesh_example.sqlmesh_example__incremental_model__1626196238 AS SELECT seed_model.id AS id, seed_model.item_id AS item_id, seed_model.ds AS ds FROM sqlmesh__sqlmesh_example.sqlmesh_example__seed_model__3609019599 AS seed_model WHERE (seed_model.ds <= '1970-01-01' AND seed_model.ds >= '1970-01-01') AND FALSE (base.py:781)
2023-06-05 21:19:00,084 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
CREATE SCHEMA IF NOT EXISTS sqlmesh__sqlmesh_example (base.py:781)
2023-06-05 21:19:00,085 - sqlmesh.core.snapshot.evaluator - INFO - Creating table 'sqlmesh__sqlmesh_example.sqlmesh_example__duration__1374773906' (evaluator.py:410)
2023-06-05 21:19:00,086 - sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
CREATE TABLE IF NOT EXISTS sqlmesh__sqlmesh_example.sqlmesh_example__duration__1374773906 AS SELECT seed_model.id AS id, seed_model.item_id AS item_id, seed_model.ds AS ds, DATE_DIFF('CURRENT_DATE', seed_model.ds, 'day') AS days_ago FROM sqlmesh__sqlmesh_example.sqlmesh_example__seed_model__3609019599 AS seed_model WHERE FALSE (base.py:781)
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 223, in sequential_apply_to_dag
    fn(node)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 161, in <lambda>
    lambda s_id: fn(snapshots_by_id[s_id]),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 260, in <lambda>
    lambda s: self._create_snapshot(s, snapshots),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 420, in _create_snapshot
    self.adapter.ctas(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 225, in ctas
    self._create_table_from_query(table_name, query_or_df, exists, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 288, in _create_table_from_query
    self._create_table(table, query, exists=exists, replace=replace, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 330, in _create_table
    self.execute(create)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 782, in execute
    self.cursor.execute(sql, **kwargs)
duckdb.BinderException: Binder Error: No function matches the given name and argument types 'date_diff(VARCHAR, VARCHAR, VARCHAR)'. You might need to add explicit type casts.
        Candidate functions:
        date_diff(VARCHAR, DATE, DATE) -> BIGINT
        date_diff(VARCHAR, TIMESTAMP, TIMESTAMP) -> BIGINT
        date_diff(VARCHAR, TIME, TIME) -> BIGINT
        date_diff(VARCHAR, TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE) -> BIGINT

LINE 1: ...em_id AS item_id, seed_model.ds AS ds, DATE_DIFF('CURRENT_DATE', seed_model.ds...
                                                  ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/bin/sqlmesh", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/cli/main.py", line 241, in plan
    context.plan(environment, restate_models=restate_models, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/core/context.py", line 714, in plan
    self.console.plan(plan, auto_apply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/core/console.py", line 301, in plan
    plan.apply()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/core/plan/definition.py", line 300, in apply
    self._apply(self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/core/context.py", line 733, in apply
    self._scheduler.create_plan_evaluator(self).evaluate(plan)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/core/plan/evaluator.py", line 73, in evaluate
    task(plan)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/core/plan/evaluator.py", line 115, in _push
    self.snapshot_evaluator.create(plan.new_snapshots, all_snapshots_by_id)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 258, in create
    concurrent_apply_to_snapshots(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 159, in concurrent_apply_to_snapshots
    return concurrent_apply_to_dag(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 194, in concurrent_apply_to_dag
    return sequential_apply_to_dag(dag, fn, raise_on_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/qry/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 226, in sequential_apply_to_dag
    raise NodeExecutionFailedError(node) from ex
sqlmesh.utils.concurrency.NodeExecutionFailedError: Execution failed for node name='sqlmesh_example.duration' identifier='4038886598'
```

I experimented with adjustments to [`_parse_date_diff`](https://github.com/tobymao/sqlglot/blob/4f31a50448ea4d84c602667b5c5ee9a788c33586/sqlglot/dialects/duckdb.py#L58) but all the arguments returned as varchar.

**Comment by GeorgeSittas** [comment]
Thanks for the report @hughcameron, I'll take a look.

**Comment by tobymao** [comment]
Hey Hugh,

Thanks for the report, but I think this is an issue with your query as opposed to SQLGlot. DuckDB requires date_diff to be called with date or timestamps but you're passing in strings. You should cast your inputs to dates before calling date_diff.

**Comment by hughcameron** [comment]
Thanks for the notes @GeorgeSittas & @tobymao 

I could get this to work by changing the seed model column definition of `ds` from `VARCHAR` to `DATE` and then making this change in sqlglot to duckdb's `TRANSFORMS` dict:

```python
            exp.DateDiff: lambda self, e: self.func(
                "DATE_DIFF", e.this, e.expression, e.args.get('unit', 'day')
            ),
```

**Comment by tobymao** [comment]
can't you just cast ds in your model sql before calling date_diff?
